// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babylon/checkpointing/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	types "github.com/cosmos/cosmos-sdk/x/staking/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgWrappedCreateValidator defines a wrapped message to create a validator
type MsgWrappedCreateValidator struct {
	Key                *BlsKey                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MsgCreateValidator *types.MsgCreateValidator `protobuf:"bytes,2,opt,name=msg_create_validator,json=msgCreateValidator,proto3" json:"msg_create_validator,omitempty"`
}

func (m *MsgWrappedCreateValidator) Reset()         { *m = MsgWrappedCreateValidator{} }
func (m *MsgWrappedCreateValidator) String() string { return proto.CompactTextString(m) }
func (*MsgWrappedCreateValidator) ProtoMessage()    {}
func (*MsgWrappedCreateValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b16c54750152c21, []int{0}
}
func (m *MsgWrappedCreateValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWrappedCreateValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWrappedCreateValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWrappedCreateValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWrappedCreateValidator.Merge(m, src)
}
func (m *MsgWrappedCreateValidator) XXX_Size() int {
	return m.Size()
}
func (m *MsgWrappedCreateValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWrappedCreateValidator.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWrappedCreateValidator proto.InternalMessageInfo

// MsgWrappedCreateValidatorResponse defines the MsgWrappedCreateValidator
// response type
type MsgWrappedCreateValidatorResponse struct {
}

func (m *MsgWrappedCreateValidatorResponse) Reset()         { *m = MsgWrappedCreateValidatorResponse{} }
func (m *MsgWrappedCreateValidatorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWrappedCreateValidatorResponse) ProtoMessage()    {}
func (*MsgWrappedCreateValidatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b16c54750152c21, []int{1}
}
func (m *MsgWrappedCreateValidatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWrappedCreateValidatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWrappedCreateValidatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWrappedCreateValidatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWrappedCreateValidatorResponse.Merge(m, src)
}
func (m *MsgWrappedCreateValidatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWrappedCreateValidatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWrappedCreateValidatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWrappedCreateValidatorResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgWrappedCreateValidator)(nil), "babylon.checkpointing.v1.MsgWrappedCreateValidator")
	proto.RegisterType((*MsgWrappedCreateValidatorResponse)(nil), "babylon.checkpointing.v1.MsgWrappedCreateValidatorResponse")
}

func init() { proto.RegisterFile("babylon/checkpointing/v1/tx.proto", fileDescriptor_6b16c54750152c21) }

var fileDescriptor_6b16c54750152c21 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xbd, 0x4b, 0xf3, 0x40,
	0x1c, 0xc7, 0x73, 0x4f, 0x79, 0x9e, 0x21, 0xcf, 0x16, 0x8a, 0xd6, 0x0c, 0xe9, 0x8b, 0x20, 0x52,
	0xf0, 0x8e, 0xa6, 0x5b, 0xdd, 0xea, 0x28, 0x5d, 0x8a, 0x28, 0x88, 0x50, 0xee, 0xd2, 0xe3, 0x1a,
	0xf2, 0x72, 0x21, 0xbf, 0x33, 0x34, 0x9b, 0x38, 0x89, 0x93, 0xab, 0x5b, 0xff, 0x84, 0xfe, 0x19,
	0x8e, 0x1d, 0x1d, 0xa5, 0x1d, 0xea, 0x9f, 0x21, 0x4d, 0x52, 0xc4, 0x6a, 0x16, 0xb7, 0x7b, 0xf9,
	0xfc, 0xbe, 0x2f, 0xdc, 0xe9, 0x4d, 0x46, 0x59, 0xea, 0xcb, 0x90, 0x38, 0x13, 0xee, 0x78, 0x91,
	0x74, 0x43, 0xe5, 0x86, 0x82, 0x24, 0x1d, 0xa2, 0xa6, 0x38, 0x8a, 0xa5, 0x92, 0x46, 0xad, 0x40,
	0xf0, 0x17, 0x04, 0x27, 0x1d, 0xb3, 0x2a, 0xa4, 0x90, 0x19, 0x44, 0x36, 0xab, 0x9c, 0x37, 0x8f,
	0x4a, 0x25, 0x99, 0x0f, 0x23, 0x8f, 0xa7, 0x05, 0x57, 0x77, 0x24, 0x04, 0x12, 0x08, 0x28, 0xea,
	0xe5, 0x00, 0xe3, 0x8a, 0x7e, 0x1a, 0x9b, 0xfb, 0x05, 0x10, 0x40, 0x36, 0x1d, 0x80, 0xc8, 0x2f,
	0x5a, 0x0b, 0xa4, 0x1f, 0x0c, 0x40, 0x5c, 0xc5, 0x34, 0x8a, 0xf8, 0xf8, 0x2c, 0xe6, 0x54, 0xf1,
	0x4b, 0xea, 0xbb, 0x63, 0xaa, 0x64, 0x6c, 0xd8, 0x7a, 0xc5, 0xe3, 0x69, 0x0d, 0x35, 0xd0, 0xf1,
	0x7f, 0xbb, 0x81, 0xcb, 0xd2, 0xe3, 0xbe, 0x0f, 0xe7, 0x3c, 0x1d, 0x6e, 0x60, 0xe3, 0x46, 0xaf,
	0x06, 0x20, 0x46, 0x4e, 0x26, 0x35, 0x4a, 0xb6, 0x5a, 0xb5, 0x3f, 0x99, 0x48, 0x1b, 0xe7, 0x49,
	0x70, 0x11, 0x15, 0x17, 0x51, 0xf1, 0x00, 0xc4, 0x8e, 0xfb, 0xd0, 0x08, 0xbe, 0x9d, 0xf5, 0x9a,
	0x0f, 0xb3, 0xba, 0xf6, 0x3e, 0xab, 0x6b, 0xf7, 0xeb, 0x79, 0xfb, 0x47, 0xa3, 0xd6, 0xa1, 0xde,
	0x2c, 0x6d, 0x34, 0xe4, 0x10, 0xc9, 0x10, 0xb8, 0xfd, 0x8c, 0xf4, 0xca, 0x00, 0x84, 0xf1, 0x88,
	0xf4, 0xbd, 0x92, 0xf2, 0xdd, 0xf2, 0xbe, 0xa5, 0xfa, 0xe6, 0xe9, 0x2f, 0x86, 0xb6, 0xa1, 0xcc,
	0xbf, 0x77, 0xeb, 0x79, 0x1b, 0xf5, 0x2f, 0x5e, 0x96, 0x16, 0x5a, 0x2c, 0x2d, 0xf4, 0xb6, 0xb4,
	0xd0, 0xd3, 0xca, 0xd2, 0x16, 0x2b, 0x4b, 0x7b, 0x5d, 0x59, 0xda, 0x75, 0x4f, 0xb8, 0x6a, 0x72,
	0xcb, 0xb0, 0x23, 0x03, 0x52, 0xf8, 0xf8, 0x94, 0xc1, 0x89, 0x2b, 0xb7, 0x5b, 0x92, 0xd8, 0x64,
	0xba, 0xf3, 0x5d, 0x54, 0x1a, 0x71, 0x60, 0xff, 0xb2, 0x07, 0xef, 0x7e, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xa4, 0x3c, 0xac, 0x36, 0xa7, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// WrappedCreateValidator defines a method for registering a new validator
	WrappedCreateValidator(ctx context.Context, in *MsgWrappedCreateValidator, opts ...grpc.CallOption) (*MsgWrappedCreateValidatorResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) WrappedCreateValidator(ctx context.Context, in *MsgWrappedCreateValidator, opts ...grpc.CallOption) (*MsgWrappedCreateValidatorResponse, error) {
	out := new(MsgWrappedCreateValidatorResponse)
	err := c.cc.Invoke(ctx, "/babylon.checkpointing.v1.Msg/WrappedCreateValidator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// WrappedCreateValidator defines a method for registering a new validator
	WrappedCreateValidator(context.Context, *MsgWrappedCreateValidator) (*MsgWrappedCreateValidatorResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) WrappedCreateValidator(ctx context.Context, req *MsgWrappedCreateValidator) (*MsgWrappedCreateValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WrappedCreateValidator not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_WrappedCreateValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWrappedCreateValidator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WrappedCreateValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/babylon.checkpointing.v1.Msg/WrappedCreateValidator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WrappedCreateValidator(ctx, req.(*MsgWrappedCreateValidator))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "babylon.checkpointing.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WrappedCreateValidator",
			Handler:    _Msg_WrappedCreateValidator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "babylon/checkpointing/v1/tx.proto",
}

func (m *MsgWrappedCreateValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWrappedCreateValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWrappedCreateValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MsgCreateValidator != nil {
		{
			size, err := m.MsgCreateValidator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Key != nil {
		{
			size, err := m.Key.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWrappedCreateValidatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWrappedCreateValidatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWrappedCreateValidatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgWrappedCreateValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Key != nil {
		l = m.Key.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MsgCreateValidator != nil {
		l = m.MsgCreateValidator.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWrappedCreateValidatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgWrappedCreateValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWrappedCreateValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWrappedCreateValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Key == nil {
				m.Key = &BlsKey{}
			}
			if err := m.Key.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgCreateValidator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MsgCreateValidator == nil {
				m.MsgCreateValidator = &types.MsgCreateValidator{}
			}
			if err := m.MsgCreateValidator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWrappedCreateValidatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWrappedCreateValidatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWrappedCreateValidatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
