version: "2"

run:
  timeout: 5m
  skip-files:
    - ".*_test\\.go$"
# TODO: enable all linters
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    # - bodyclose
    # - containedctx
    # - contextcheck
    - decorder
    # - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    # - errorlint
    # - exhaustive
    # - forbidigo
    # - forcetypeassert
    - goconst
    - gocritic
    # - gocyclo
    - goheader
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    # - maintidx
    - makezero
    - misspell
    - nakedret
    - nilerr
    # - nlreturn
    - noctx
    - nosprintfhostport
    # - paralleltest
    - reassign
    # - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    # - stylecheck
    - tenv
    - testableexamples
    # - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - unused
    - wastedassign
    - whitespace
    # - wrapcheck
  exclusions:
    paths:
      - e2etest
      - "test/"
      - "_test.go"

issues:
  max-same-issues: 0

