version: "2"

run:
  timeout: 5m

linters:
  # v2 replaces `disable-all: true` with an explicit default
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    # - bodyclose
    # - containedctx
    # - contextcheck
    - decorder
    # - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    # - errorlint
    # - exhaustive
    - forbidigo
    # - forcetypeassert
    - goconst
    - gocritic
    # - gocyclo
    - goheader
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    # - maintidx
    - makezero
    - misspell
    - nakedret
    - nilerr
    # - nlreturn
    - noctx
    - nosprintfhostport
    # - paralleltest
    - reassign
    # - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    # - stylecheck
    - testableexamples
    # - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - unused
    - wastedassign
    - whitespace
    # - wrapcheck

issues:
  max-same-issues: 0
  # If you only want to suppress reports from a dir (not skip loading it),
  # keep using issues.exclude-dirs in v2:
  exclude-dirs:
    - e2etest
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path-except: _test\.go
      linters:
        - forbidigo
