version: 2
project_name: babylon

env:
  - CGO_ENABLED=1
  - CC=/opt/musl-cross/bin/x86_64-linux-musl-gcc
  - LD=/opt/musl-cross/bin/x86_64-linux-musl-ld
  - CGO_LDFLAGS=-L/lib

before:
  hooks:
    - wget -nc https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /lib/libwasmvm_muslc.x86_64.a
    - cp -n -u /lib/libwasmvm_muslc.x86_64.a /lib/libwasmvm_muslc.a
    - curl -LO https://musl.cc/x86_64-linux-musl-cross.tgz
    - tar xf x86_64-linux-musl-cross.tgz
    - mv -n -u x86_64-linux-musl-cross /opt/musl-cross

builds:
  - id: babylond-linux-amd64
    main: ./cmd/babylond/main.go
    binary: babylond
    builder: go
    gobinary: "go"
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=babylon
      - -X github.com/cosmos/cosmos-sdk/version.AppName=babylond
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=ledger,muslc,mainnet
      - -linkmode=external
      - -w -s
      - -extldflags "-Wl,-z,muldefs -static -z noexecstack"
    tags:
      - ledger
      - muslc
      - mainnet

  - id: babylond-testnet-linux-amd64
    main: ./cmd/babylond/main.go
    binary: babylond
    builder: go
    gobinary: "go"
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=babylon
      - -X github.com/cosmos/cosmos-sdk/version.AppName=babylond
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=ledger,muslc,testnet
      - -linkmode=external
      - -w -s
      - -extldflags "-Wl,-z,muldefs -static -z noexecstack"
    tags:
      - ledger
      - muslc
      - testnet

archives:
  - id: zipped
    builds:
      - babylond-linux-amd64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    wrap_in_directory: false
    files:
      - none*
  - id: zipped-testnet
    builds:
      - babylond-testnet-linux-amd64
    name_template: "{{.ProjectName}}-testnet-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    wrap_in_directory: false
    files:
      - none*
  - id: binaries
    builds:
      - babylond-linux-amd64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    wrap_in_directory: false
    files:
      - none*
  - id: binaries-testnet
    builds:
      - babylond-testnet-linux-amd64
    name_template: "{{.ProjectName}}-testnet-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    wrap_in_directory: false
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: babylonlabs-io
    name: babylon

# Docs: https://goreleaser.com/customization/changelog/
changelog:
  disable: true

dist: dist

git:
  prerelease_suffix: "-rc"