queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>1"
      - base=main
      - label=A:automerge
    merge_conditions:
      - "#approved-reviews-by>1"
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash
pull_request_rules:
  - name: backport changes to v3.x branch
    conditions:
      - base=main
      - label=backport-to-release/v3.x
    actions:
      backport:
        branches:
          - release/v3.x
  - name: backport changes to v2.2.x, v2.3.x, v3.x
    conditions:
      - base=main
      - label=backport-to-release/v2.2.x
    actions:
      backport:
        branches:
          - release/v2.2.x
          - release/v2.3.x
          - release/v3.x
  - name: backport changes to v2.3.x, v3.x
    conditions:
      - base=main
      - label=backport-to-release/v2.3.x
    actions:
      backport:
        branches:
          - release/v2.3.x
          - release/v3.x
  - name: automerge to main with label automerge and branch protection passing
    conditions: []
    actions:
      queue:
