// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babylon/zoneconcierge/v1/packet.proto

package types

import (
	fmt "fmt"
	types4 "github.com/babylonlabs-io/babylon/x/btccheckpoint/types"
	types1 "github.com/babylonlabs-io/babylon/x/btclightclient/types"
	types "github.com/babylonlabs-io/babylon/x/btcstaking/types"
	types3 "github.com/babylonlabs-io/babylon/x/checkpointing/types"
	types2 "github.com/babylonlabs-io/babylon/x/epoching/types"
	types5 "github.com/babylonlabs-io/babylon/x/finality/types"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ZoneconciergePacketData is the message that defines the IBC packets of
// ZoneConcierge
type ZoneconciergePacketData struct {
	// packet is the actual message carried in the IBC packet
	//
	// Types that are valid to be assigned to Packet:
	//	*ZoneconciergePacketData_BtcTimestamp
	//	*ZoneconciergePacketData_BtcStaking
	//	*ZoneconciergePacketData_ConsumerRegister
	//	*ZoneconciergePacketData_ConsumerSlashing
	Packet isZoneconciergePacketData_Packet `protobuf_oneof:"packet"`
}

func (m *ZoneconciergePacketData) Reset()         { *m = ZoneconciergePacketData{} }
func (m *ZoneconciergePacketData) String() string { return proto.CompactTextString(m) }
func (*ZoneconciergePacketData) ProtoMessage()    {}
func (*ZoneconciergePacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_be12e124c5c4fdb9, []int{0}
}
func (m *ZoneconciergePacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ZoneconciergePacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ZoneconciergePacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ZoneconciergePacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneconciergePacketData.Merge(m, src)
}
func (m *ZoneconciergePacketData) XXX_Size() int {
	return m.Size()
}
func (m *ZoneconciergePacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneconciergePacketData.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneconciergePacketData proto.InternalMessageInfo

type isZoneconciergePacketData_Packet interface {
	isZoneconciergePacketData_Packet()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ZoneconciergePacketData_BtcTimestamp struct {
	BtcTimestamp *BTCTimestamp `protobuf:"bytes,1,opt,name=btc_timestamp,json=btcTimestamp,proto3,oneof" json:"btc_timestamp,omitempty"`
}
type ZoneconciergePacketData_BtcStaking struct {
	BtcStaking *types.BTCStakingIBCPacket `protobuf:"bytes,2,opt,name=btc_staking,json=btcStaking,proto3,oneof" json:"btc_staking,omitempty"`
}
type ZoneconciergePacketData_ConsumerRegister struct {
	ConsumerRegister *ConsumerRegisterIBCPacket `protobuf:"bytes,3,opt,name=consumer_register,json=consumerRegister,proto3,oneof" json:"consumer_register,omitempty"`
}
type ZoneconciergePacketData_ConsumerSlashing struct {
	ConsumerSlashing *ConsumerSlashingIBCPacket `protobuf:"bytes,4,opt,name=consumer_slashing,json=consumerSlashing,proto3,oneof" json:"consumer_slashing,omitempty"`
}

func (*ZoneconciergePacketData_BtcTimestamp) isZoneconciergePacketData_Packet()     {}
func (*ZoneconciergePacketData_BtcStaking) isZoneconciergePacketData_Packet()       {}
func (*ZoneconciergePacketData_ConsumerRegister) isZoneconciergePacketData_Packet() {}
func (*ZoneconciergePacketData_ConsumerSlashing) isZoneconciergePacketData_Packet() {}

func (m *ZoneconciergePacketData) GetPacket() isZoneconciergePacketData_Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *ZoneconciergePacketData) GetBtcTimestamp() *BTCTimestamp {
	if x, ok := m.GetPacket().(*ZoneconciergePacketData_BtcTimestamp); ok {
		return x.BtcTimestamp
	}
	return nil
}

func (m *ZoneconciergePacketData) GetBtcStaking() *types.BTCStakingIBCPacket {
	if x, ok := m.GetPacket().(*ZoneconciergePacketData_BtcStaking); ok {
		return x.BtcStaking
	}
	return nil
}

func (m *ZoneconciergePacketData) GetConsumerRegister() *ConsumerRegisterIBCPacket {
	if x, ok := m.GetPacket().(*ZoneconciergePacketData_ConsumerRegister); ok {
		return x.ConsumerRegister
	}
	return nil
}

func (m *ZoneconciergePacketData) GetConsumerSlashing() *ConsumerSlashingIBCPacket {
	if x, ok := m.GetPacket().(*ZoneconciergePacketData_ConsumerSlashing); ok {
		return x.ConsumerSlashing
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ZoneconciergePacketData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ZoneconciergePacketData_BtcTimestamp)(nil),
		(*ZoneconciergePacketData_BtcStaking)(nil),
		(*ZoneconciergePacketData_ConsumerRegister)(nil),
		(*ZoneconciergePacketData_ConsumerSlashing)(nil),
	}
}

// BTCTimestamp is a BTC timestamp that carries information of a BTC-finalised epoch
// It includes a number of BTC headers, a raw checkpoint, an epoch metadata, and
// a CZ header if there exists CZ headers checkpointed to this epoch.
// Upon a newly finalised epoch in Babylon, Babylon will send a BTC timestamp to each
// Cosmos zone that has phase-2 integration with Babylon via IBC.
type BTCTimestamp struct {
	// header is the last CZ header in the finalized Babylon epoch
	Header *IndexedHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// btc_headers is BTC headers between
	// - the block AFTER the common ancestor of BTC tip at epoch `lastFinalizedEpoch-1` and BTC tip at epoch `lastFinalizedEpoch`
	// - BTC tip at epoch `lastFinalizedEpoch`
	// where `lastFinalizedEpoch` is the last finalised epoch in Babylon
	BtcHeaders []*types1.BTCHeaderInfo `protobuf:"bytes,2,rep,name=btc_headers,json=btcHeaders,proto3" json:"btc_headers,omitempty"`
	// epoch_info is the metadata of the sealed epoch
	EpochInfo *types2.Epoch `protobuf:"bytes,3,opt,name=epoch_info,json=epochInfo,proto3" json:"epoch_info,omitempty"`
	// raw_checkpoint is the raw checkpoint that seals this epoch
	RawCheckpoint *types3.RawCheckpoint `protobuf:"bytes,4,opt,name=raw_checkpoint,json=rawCheckpoint,proto3" json:"raw_checkpoint,omitempty"`
	// btc_submission_key is position of two BTC txs that include the raw checkpoint of this epoch
	BtcSubmissionKey *types4.SubmissionKey `protobuf:"bytes,5,opt,name=btc_submission_key,json=btcSubmissionKey,proto3" json:"btc_submission_key,omitempty"`
	//
	//Proofs that the header is finalized
	Proof *ProofFinalizedChainInfo `protobuf:"bytes,6,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *BTCTimestamp) Reset()         { *m = BTCTimestamp{} }
func (m *BTCTimestamp) String() string { return proto.CompactTextString(m) }
func (*BTCTimestamp) ProtoMessage()    {}
func (*BTCTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_be12e124c5c4fdb9, []int{1}
}
func (m *BTCTimestamp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BTCTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BTCTimestamp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BTCTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BTCTimestamp.Merge(m, src)
}
func (m *BTCTimestamp) XXX_Size() int {
	return m.Size()
}
func (m *BTCTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_BTCTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_BTCTimestamp proto.InternalMessageInfo

func (m *BTCTimestamp) GetHeader() *IndexedHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BTCTimestamp) GetBtcHeaders() []*types1.BTCHeaderInfo {
	if m != nil {
		return m.BtcHeaders
	}
	return nil
}

func (m *BTCTimestamp) GetEpochInfo() *types2.Epoch {
	if m != nil {
		return m.EpochInfo
	}
	return nil
}

func (m *BTCTimestamp) GetRawCheckpoint() *types3.RawCheckpoint {
	if m != nil {
		return m.RawCheckpoint
	}
	return nil
}

func (m *BTCTimestamp) GetBtcSubmissionKey() *types4.SubmissionKey {
	if m != nil {
		return m.BtcSubmissionKey
	}
	return nil
}

func (m *BTCTimestamp) GetProof() *ProofFinalizedChainInfo {
	if m != nil {
		return m.Proof
	}
	return nil
}

// ConsumerRegisterIBCPacket defines the packet data for Consumer registration
type ConsumerRegisterIBCPacket struct {
	// consumer_name is a unique identifier for the consumer chain
	ConsumerName string `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	// consumer_description is a brief explanation of the consumer chain's purpose
	ConsumerDescription string `protobuf:"bytes,2,opt,name=consumer_description,json=consumerDescription,proto3" json:"consumer_description,omitempty"`
}

func (m *ConsumerRegisterIBCPacket) Reset()         { *m = ConsumerRegisterIBCPacket{} }
func (m *ConsumerRegisterIBCPacket) String() string { return proto.CompactTextString(m) }
func (*ConsumerRegisterIBCPacket) ProtoMessage()    {}
func (*ConsumerRegisterIBCPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_be12e124c5c4fdb9, []int{2}
}
func (m *ConsumerRegisterIBCPacket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsumerRegisterIBCPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsumerRegisterIBCPacket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsumerRegisterIBCPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerRegisterIBCPacket.Merge(m, src)
}
func (m *ConsumerRegisterIBCPacket) XXX_Size() int {
	return m.Size()
}
func (m *ConsumerRegisterIBCPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerRegisterIBCPacket.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerRegisterIBCPacket proto.InternalMessageInfo

func (m *ConsumerRegisterIBCPacket) GetConsumerName() string {
	if m != nil {
		return m.ConsumerName
	}
	return ""
}

func (m *ConsumerRegisterIBCPacket) GetConsumerDescription() string {
	if m != nil {
		return m.ConsumerDescription
	}
	return ""
}

// ConsumerSlashingIBCPacket defines the slashing information that a Consumer sends to Babylon's ZoneConcierge upon a
// Consumer slashing event.
// It includes the FP public key, the Consumer block height at the slashing event, and the double sign evidence.
type ConsumerSlashingIBCPacket struct {
	/// evidence is the FP slashing evidence that the Consumer sends to Babylon
	Evidence *types5.Evidence `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence,omitempty"`
}

func (m *ConsumerSlashingIBCPacket) Reset()         { *m = ConsumerSlashingIBCPacket{} }
func (m *ConsumerSlashingIBCPacket) String() string { return proto.CompactTextString(m) }
func (*ConsumerSlashingIBCPacket) ProtoMessage()    {}
func (*ConsumerSlashingIBCPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_be12e124c5c4fdb9, []int{3}
}
func (m *ConsumerSlashingIBCPacket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsumerSlashingIBCPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsumerSlashingIBCPacket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsumerSlashingIBCPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerSlashingIBCPacket.Merge(m, src)
}
func (m *ConsumerSlashingIBCPacket) XXX_Size() int {
	return m.Size()
}
func (m *ConsumerSlashingIBCPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerSlashingIBCPacket.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerSlashingIBCPacket proto.InternalMessageInfo

func (m *ConsumerSlashingIBCPacket) GetEvidence() *types5.Evidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func init() {
	proto.RegisterType((*ZoneconciergePacketData)(nil), "babylon.zoneconcierge.v1.ZoneconciergePacketData")
	proto.RegisterType((*BTCTimestamp)(nil), "babylon.zoneconcierge.v1.BTCTimestamp")
	proto.RegisterType((*ConsumerRegisterIBCPacket)(nil), "babylon.zoneconcierge.v1.ConsumerRegisterIBCPacket")
	proto.RegisterType((*ConsumerSlashingIBCPacket)(nil), "babylon.zoneconcierge.v1.ConsumerSlashingIBCPacket")
}

func init() {
	proto.RegisterFile("babylon/zoneconcierge/v1/packet.proto", fileDescriptor_be12e124c5c4fdb9)
}

var fileDescriptor_be12e124c5c4fdb9 = []byte{
	// 654 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xc1, 0x6f, 0xd3, 0x3e,
	0x14, 0x6e, 0xd7, 0xdf, 0xaa, 0xcd, 0xdb, 0x7e, 0x1a, 0x06, 0x89, 0x30, 0x89, 0x6a, 0x2a, 0x02,
	0x06, 0x1a, 0xa9, 0xba, 0x1d, 0xd0, 0x4e, 0x48, 0xed, 0x80, 0x55, 0x68, 0xd3, 0xc8, 0x06, 0x87,
	0x5d, 0x2a, 0xc7, 0x7d, 0x6d, 0xad, 0x36, 0x76, 0x14, 0x7b, 0xdd, 0xba, 0xff, 0x80, 0x1b, 0xff,
	0x14, 0x12, 0xc7, 0x1d, 0x39, 0xa2, 0xf5, 0x1f, 0x41, 0x71, 0x1c, 0x37, 0xe9, 0x88, 0xc4, 0x25,
	0xca, 0x7b, 0xfe, 0xde, 0xf7, 0xec, 0xcf, 0xdf, 0x33, 0x7a, 0xee, 0x13, 0x7f, 0x3a, 0x16, 0xbc,
	0x71, 0x23, 0x38, 0x50, 0xc1, 0x29, 0x83, 0x68, 0x00, 0x8d, 0x49, 0xb3, 0x11, 0x12, 0x3a, 0x02,
	0xe5, 0x86, 0x91, 0x50, 0x02, 0x3b, 0x06, 0xe6, 0xe6, 0x60, 0xee, 0xa4, 0xb9, 0xb5, 0x9b, 0x12,
	0xf8, 0x8a, 0xd2, 0x21, 0xd0, 0x51, 0x28, 0x18, 0x57, 0x31, 0x41, 0x2e, 0x91, 0xf0, 0x6c, 0xb9,
	0x19, 0xf4, 0x98, 0x0d, 0x86, 0xf1, 0x17, 0x2c, 0x3c, 0x93, 0x31, 0xf8, 0x7a, 0x06, 0x2f, 0x15,
	0x19, 0x31, 0x3e, 0x58, 0xdc, 0xdb, 0xd6, 0xab, 0x14, 0x33, 0xef, 0x66, 0x60, 0xf7, 0xda, 0x5b,
	0x3a, 0x08, 0x05, 0x1d, 0x1a, 0x54, 0xfa, 0x6f, 0x30, 0xbb, 0x85, 0x8a, 0xe4, 0xcf, 0xbe, 0xc0,
	0xd8, 0x67, 0x9c, 0x8c, 0x99, 0x9a, 0xc6, 0xc0, 0xf4, 0x3f, 0xc1, 0xd4, 0xbf, 0x55, 0xd0, 0xe3,
	0x8b, 0x6c, 0xed, 0xa9, 0xde, 0xfe, 0x21, 0x51, 0x04, 0x1f, 0xa3, 0x0d, 0x5f, 0xd1, 0xae, 0x62,
	0x01, 0x48, 0x45, 0x82, 0xd0, 0x29, 0x6f, 0x97, 0x77, 0xd6, 0xf6, 0x5e, 0xb8, 0x45, 0x82, 0xbb,
	0xad, 0xf3, 0xf6, 0x79, 0x8a, 0x3e, 0x2a, 0x79, 0xeb, 0xbe, 0xa2, 0x36, 0xc6, 0xc7, 0x68, 0x2d,
	0xa6, 0x33, 0x52, 0x39, 0x4b, 0x9a, 0xec, 0xb5, 0x25, 0x9b, 0xab, 0x68, 0x98, 0xce, 0x92, 0xa8,
	0xd3, 0x6a, 0x27, 0x7b, 0x3a, 0x2a, 0x79, 0xc8, 0x57, 0xd4, 0xa4, 0xb1, 0x8f, 0x1e, 0x50, 0xc1,
	0xe5, 0x65, 0x00, 0x51, 0x37, 0x82, 0x01, 0x93, 0x0a, 0x22, 0xa7, 0xa2, 0x49, 0xf7, 0x8b, 0x77,
	0xd8, 0x36, 0x25, 0x9e, 0xa9, 0xc8, 0xb2, 0x6f, 0xd2, 0x85, 0xc5, 0x5c, 0x0f, 0x39, 0x26, 0x32,
	0xbe, 0x0a, 0xe7, 0xbf, 0x7f, 0xed, 0x71, 0x66, 0x2a, 0xfe, 0xda, 0x23, 0x5d, 0x6c, 0xad, 0xa0,
	0x6a, 0x62, 0x99, 0xfa, 0x8f, 0x0a, 0x5a, 0xcf, 0x2a, 0x88, 0xdf, 0xa1, 0xea, 0x10, 0x48, 0x0f,
	0x22, 0xa3, 0xfc, 0xcb, 0xe2, 0x9e, 0x1d, 0xde, 0x83, 0x6b, 0xe8, 0x1d, 0x69, 0xb8, 0x67, 0xca,
	0x70, 0x27, 0x91, 0x3c, 0x89, 0xa4, 0xb3, 0xb4, 0x5d, 0xd9, 0x59, 0xdb, 0xdb, 0xc9, 0x4a, 0x9e,
	0xb5, 0x75, 0x22, 0x7b, 0x42, 0xd1, 0xe1, 0x7d, 0xa1, 0xe5, 0x4e, 0x42, 0x89, 0x0f, 0x10, 0xd2,
	0x66, 0xec, 0x32, 0xde, 0x17, 0x46, 0x67, 0x3b, 0x32, 0xae, 0xf5, 0xe9, 0xa4, 0xe9, 0xbe, 0x8f,
	0xff, 0xbd, 0x55, 0x9d, 0x8a, 0x69, 0xf0, 0x09, 0xfa, 0x3f, 0x22, 0x57, 0xdd, 0xb9, 0xe3, 0x8d,
	0x84, 0xf3, 0xe3, 0xe4, 0xa6, 0x23, 0xe6, 0xf0, 0xc8, 0x55, 0xdb, 0xe6, 0xbc, 0x8d, 0x28, 0x1b,
	0xe2, 0x2f, 0x08, 0x6b, 0x23, 0x5d, 0xfa, 0x01, 0x93, 0x92, 0x09, 0xde, 0x1d, 0xc1, 0xd4, 0x59,
	0x5e, 0xe0, 0xcc, 0x8f, 0xf8, 0xa4, 0xe9, 0x9e, 0x59, 0xfc, 0x27, 0x98, 0x7a, 0x9b, 0xb1, 0x95,
	0xb2, 0x19, 0xfc, 0x11, 0x2d, 0x87, 0x91, 0x10, 0x7d, 0xa7, 0xaa, 0x99, 0x9a, 0xc5, 0x62, 0x9f,
	0xc6, 0xb0, 0x0f, 0x7a, 0x90, 0x6e, 0xa0, 0xd7, 0x1e, 0x12, 0xc6, 0xb5, 0x5e, 0x49, 0x7d, 0x5d,
	0xa2, 0x27, 0x85, 0x36, 0xc3, 0xcf, 0xd0, 0x86, 0xb5, 0x14, 0x27, 0x01, 0xe8, 0xab, 0x5d, 0xf5,
	0xd6, 0xd3, 0xe4, 0x09, 0x09, 0x00, 0x37, 0xd1, 0x23, 0x0b, 0xea, 0x81, 0xa4, 0x11, 0x0b, 0x15,
	0x13, 0x5c, 0xcf, 0xcc, 0xaa, 0xf7, 0x30, 0x5d, 0x3b, 0x9c, 0x2f, 0xd5, 0xbf, 0xce, 0x9b, 0xde,
	0xf3, 0x1d, 0x3e, 0x40, 0x2b, 0x30, 0x61, 0x3d, 0xe0, 0x14, 0x8c, 0x95, 0x9e, 0xda, 0xd3, 0xd9,
	0x07, 0x21, 0xbe, 0x3a, 0x03, 0xf2, 0x2c, 0xbc, 0xf5, 0xf9, 0xe7, 0x5d, 0xad, 0x7c, 0x7b, 0x57,
	0x2b, 0xff, 0xbe, 0xab, 0x95, 0xbf, 0xcf, 0x6a, 0xa5, 0xdb, 0x59, 0xad, 0xf4, 0x6b, 0x56, 0x2b,
	0x5d, 0xbc, 0x1d, 0x30, 0x35, 0xbc, 0xf4, 0x5d, 0x2a, 0x82, 0x86, 0x21, 0x1b, 0x13, 0x5f, 0xbe,
	0x61, 0x22, 0x0d, 0x1b, 0xd7, 0x0b, 0x0f, 0x95, 0x9a, 0x86, 0x20, 0xfd, 0xaa, 0x7e, 0x7a, 0xf6,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x58, 0xfb, 0x0e, 0xb3, 0xe0, 0x05, 0x00, 0x00,
}

func (m *ZoneconciergePacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ZoneconciergePacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ZoneconciergePacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Packet != nil {
		{
			size := m.Packet.Size()
			i -= size
			if _, err := m.Packet.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *ZoneconciergePacketData_BtcTimestamp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ZoneconciergePacketData_BtcTimestamp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.BtcTimestamp != nil {
		{
			size, err := m.BtcTimestamp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *ZoneconciergePacketData_BtcStaking) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ZoneconciergePacketData_BtcStaking) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.BtcStaking != nil {
		{
			size, err := m.BtcStaking.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *ZoneconciergePacketData_ConsumerRegister) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ZoneconciergePacketData_ConsumerRegister) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ConsumerRegister != nil {
		{
			size, err := m.ConsumerRegister.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *ZoneconciergePacketData_ConsumerSlashing) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ZoneconciergePacketData_ConsumerSlashing) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ConsumerSlashing != nil {
		{
			size, err := m.ConsumerSlashing.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *BTCTimestamp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BTCTimestamp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BTCTimestamp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Proof != nil {
		{
			size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.BtcSubmissionKey != nil {
		{
			size, err := m.BtcSubmissionKey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.RawCheckpoint != nil {
		{
			size, err := m.RawCheckpoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.EpochInfo != nil {
		{
			size, err := m.EpochInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BtcHeaders) > 0 {
		for iNdEx := len(m.BtcHeaders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BtcHeaders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPacket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Header != nil {
		{
			size, err := m.Header.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConsumerRegisterIBCPacket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsumerRegisterIBCPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerRegisterIBCPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConsumerDescription) > 0 {
		i -= len(m.ConsumerDescription)
		copy(dAtA[i:], m.ConsumerDescription)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.ConsumerDescription)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ConsumerName) > 0 {
		i -= len(m.ConsumerName)
		copy(dAtA[i:], m.ConsumerName)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.ConsumerName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConsumerSlashingIBCPacket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsumerSlashingIBCPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerSlashingIBCPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Evidence != nil {
		{
			size, err := m.Evidence.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ZoneconciergePacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Packet != nil {
		n += m.Packet.Size()
	}
	return n
}

func (m *ZoneconciergePacketData_BtcTimestamp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BtcTimestamp != nil {
		l = m.BtcTimestamp.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *ZoneconciergePacketData_BtcStaking) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BtcStaking != nil {
		l = m.BtcStaking.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *ZoneconciergePacketData_ConsumerRegister) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ConsumerRegister != nil {
		l = m.ConsumerRegister.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *ZoneconciergePacketData_ConsumerSlashing) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ConsumerSlashing != nil {
		l = m.ConsumerSlashing.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *BTCTimestamp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	if len(m.BtcHeaders) > 0 {
		for _, e := range m.BtcHeaders {
			l = e.Size()
			n += 1 + l + sovPacket(uint64(l))
		}
	}
	if m.EpochInfo != nil {
		l = m.EpochInfo.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	if m.RawCheckpoint != nil {
		l = m.RawCheckpoint.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	if m.BtcSubmissionKey != nil {
		l = m.BtcSubmissionKey.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	if m.Proof != nil {
		l = m.Proof.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *ConsumerRegisterIBCPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConsumerName)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.ConsumerDescription)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *ConsumerSlashingIBCPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Evidence != nil {
		l = m.Evidence.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ZoneconciergePacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ZoneconciergePacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ZoneconciergePacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcTimestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &BTCTimestamp{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &ZoneconciergePacketData_BtcTimestamp{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcStaking", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &types.BTCStakingIBCPacket{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &ZoneconciergePacketData_BtcStaking{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerRegister", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ConsumerRegisterIBCPacket{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &ZoneconciergePacketData_ConsumerRegister{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerSlashing", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ConsumerSlashingIBCPacket{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &ZoneconciergePacketData_ConsumerSlashing{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BTCTimestamp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BTCTimestamp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BTCTimestamp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &IndexedHeader{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcHeaders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcHeaders = append(m.BtcHeaders, &types1.BTCHeaderInfo{})
			if err := m.BtcHeaders[len(m.BtcHeaders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EpochInfo == nil {
				m.EpochInfo = &types2.Epoch{}
			}
			if err := m.EpochInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawCheckpoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RawCheckpoint == nil {
				m.RawCheckpoint = &types3.RawCheckpoint{}
			}
			if err := m.RawCheckpoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcSubmissionKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BtcSubmissionKey == nil {
				m.BtcSubmissionKey = &types4.SubmissionKey{}
			}
			if err := m.BtcSubmissionKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proof == nil {
				m.Proof = &ProofFinalizedChainInfo{}
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsumerRegisterIBCPacket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsumerRegisterIBCPacket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsumerRegisterIBCPacket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsumerSlashingIBCPacket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsumerSlashingIBCPacket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsumerSlashingIBCPacket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Evidence == nil {
				m.Evidence = &types5.Evidence{}
			}
			if err := m.Evidence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
