// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babylon/zoneconcierge/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	types2 "github.com/babylonlabs-io/babylon/v3/x/btccheckpoint/types"
	types1 "github.com/babylonlabs-io/babylon/v3/x/checkpointing/types"
	types "github.com/babylonlabs-io/babylon/v3/x/epoching/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd665af90102da38, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd665af90102da38, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryFinalizedBSNsInfoRequest is request type for the
// Query/FinalizedBSNsInfo RPC method.
type QueryFinalizedBSNsInfoRequest struct {
	// consumer_ids is the list of ids of BSNs
	ConsumerIds []string `protobuf:"bytes,1,rep,name=consumer_ids,json=consumerIds,proto3" json:"consumer_ids,omitempty"`
	// prove indicates whether the querier wants to get proofs of this timestamp
	Prove bool `protobuf:"varint,2,opt,name=prove,proto3" json:"prove,omitempty"`
}

func (m *QueryFinalizedBSNsInfoRequest) Reset()         { *m = QueryFinalizedBSNsInfoRequest{} }
func (m *QueryFinalizedBSNsInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFinalizedBSNsInfoRequest) ProtoMessage()    {}
func (*QueryFinalizedBSNsInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd665af90102da38, []int{2}
}
func (m *QueryFinalizedBSNsInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFinalizedBSNsInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFinalizedBSNsInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFinalizedBSNsInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFinalizedBSNsInfoRequest.Merge(m, src)
}
func (m *QueryFinalizedBSNsInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFinalizedBSNsInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFinalizedBSNsInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFinalizedBSNsInfoRequest proto.InternalMessageInfo

func (m *QueryFinalizedBSNsInfoRequest) GetConsumerIds() []string {
	if m != nil {
		return m.ConsumerIds
	}
	return nil
}

func (m *QueryFinalizedBSNsInfoRequest) GetProve() bool {
	if m != nil {
		return m.Prove
	}
	return false
}

// QueryFinalizedBSNsInfoResponse is response type for the
// Query/FinalizedBSNsInfo RPC method.
type QueryFinalizedBSNsInfoResponse struct {
	FinalizedBsnsData []*FinalizedBSNData `protobuf:"bytes,1,rep,name=finalized_bsns_data,json=finalizedBsnsData,proto3" json:"finalized_bsns_data,omitempty"`
}

func (m *QueryFinalizedBSNsInfoResponse) Reset()         { *m = QueryFinalizedBSNsInfoResponse{} }
func (m *QueryFinalizedBSNsInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFinalizedBSNsInfoResponse) ProtoMessage()    {}
func (*QueryFinalizedBSNsInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd665af90102da38, []int{3}
}
func (m *QueryFinalizedBSNsInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFinalizedBSNsInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFinalizedBSNsInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFinalizedBSNsInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFinalizedBSNsInfoResponse.Merge(m, src)
}
func (m *QueryFinalizedBSNsInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFinalizedBSNsInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFinalizedBSNsInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFinalizedBSNsInfoResponse proto.InternalMessageInfo

func (m *QueryFinalizedBSNsInfoResponse) GetFinalizedBsnsData() []*FinalizedBSNData {
	if m != nil {
		return m.FinalizedBsnsData
	}
	return nil
}

// FinalizedBSNData contains the finalized BSN data for a BSN
type FinalizedBSNData struct {
	ConsumerId string `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// The latest finalized header for this BSN
	LatestFinalizedHeader *IndexedHeader `protobuf:"bytes,2,opt,name=latest_finalized_header,json=latestFinalizedHeader,proto3" json:"latest_finalized_header,omitempty"`
	// The epoch in which this header was finalized
	EpochInfo *types.Epoch `protobuf:"bytes,3,opt,name=epoch_info,json=epochInfo,proto3" json:"epoch_info,omitempty"`
	// The raw checkpoint of this epoch
	RawCheckpoint *types1.RawCheckpoint `protobuf:"bytes,4,opt,name=raw_checkpoint,json=rawCheckpoint,proto3" json:"raw_checkpoint,omitempty"`
	// The submission key for the checkpoint
	BtcSubmissionKey *types2.SubmissionKey `protobuf:"bytes,5,opt,name=btc_submission_key,json=btcSubmissionKey,proto3" json:"btc_submission_key,omitempty"`
	// Proofs of finality
	Proof *ProofFinalizedHeader `protobuf:"bytes,6,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *FinalizedBSNData) Reset()         { *m = FinalizedBSNData{} }
func (m *FinalizedBSNData) String() string { return proto.CompactTextString(m) }
func (*FinalizedBSNData) ProtoMessage()    {}
func (*FinalizedBSNData) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd665af90102da38, []int{4}
}
func (m *FinalizedBSNData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FinalizedBSNData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FinalizedBSNData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FinalizedBSNData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizedBSNData.Merge(m, src)
}
func (m *FinalizedBSNData) XXX_Size() int {
	return m.Size()
}
func (m *FinalizedBSNData) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizedBSNData.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizedBSNData proto.InternalMessageInfo

func (m *FinalizedBSNData) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

func (m *FinalizedBSNData) GetLatestFinalizedHeader() *IndexedHeader {
	if m != nil {
		return m.LatestFinalizedHeader
	}
	return nil
}

func (m *FinalizedBSNData) GetEpochInfo() *types.Epoch {
	if m != nil {
		return m.EpochInfo
	}
	return nil
}

func (m *FinalizedBSNData) GetRawCheckpoint() *types1.RawCheckpoint {
	if m != nil {
		return m.RawCheckpoint
	}
	return nil
}

func (m *FinalizedBSNData) GetBtcSubmissionKey() *types2.SubmissionKey {
	if m != nil {
		return m.BtcSubmissionKey
	}
	return nil
}

func (m *FinalizedBSNData) GetProof() *ProofFinalizedHeader {
	if m != nil {
		return m.Proof
	}
	return nil
}

// QueryLatestEpochHeadersRequest is request type for the
// QueryLatestEpochHeadersRequest RPC method.
type QueryLatestEpochHeaderRequest struct {
	ConsumerId string `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
}

func (m *QueryLatestEpochHeaderRequest) Reset()         { *m = QueryLatestEpochHeaderRequest{} }
func (m *QueryLatestEpochHeaderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLatestEpochHeaderRequest) ProtoMessage()    {}
func (*QueryLatestEpochHeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd665af90102da38, []int{5}
}
func (m *QueryLatestEpochHeaderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestEpochHeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestEpochHeaderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestEpochHeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestEpochHeaderRequest.Merge(m, src)
}
func (m *QueryLatestEpochHeaderRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestEpochHeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestEpochHeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestEpochHeaderRequest proto.InternalMessageInfo

func (m *QueryLatestEpochHeaderRequest) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

// QueryLatestEpochHeadersResponse is request type for the
// QueryLatestEpochHeadersResponse RPC method.
type QueryLatestEpochHeaderResponse struct {
	Header *IndexedHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (m *QueryLatestEpochHeaderResponse) Reset()         { *m = QueryLatestEpochHeaderResponse{} }
func (m *QueryLatestEpochHeaderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLatestEpochHeaderResponse) ProtoMessage()    {}
func (*QueryLatestEpochHeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd665af90102da38, []int{6}
}
func (m *QueryLatestEpochHeaderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestEpochHeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestEpochHeaderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestEpochHeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestEpochHeaderResponse.Merge(m, src)
}
func (m *QueryLatestEpochHeaderResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestEpochHeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestEpochHeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestEpochHeaderResponse proto.InternalMessageInfo

func (m *QueryLatestEpochHeaderResponse) GetHeader() *IndexedHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "babylon.zoneconcierge.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "babylon.zoneconcierge.v1.QueryParamsResponse")
	proto.RegisterType((*QueryFinalizedBSNsInfoRequest)(nil), "babylon.zoneconcierge.v1.QueryFinalizedBSNsInfoRequest")
	proto.RegisterType((*QueryFinalizedBSNsInfoResponse)(nil), "babylon.zoneconcierge.v1.QueryFinalizedBSNsInfoResponse")
	proto.RegisterType((*FinalizedBSNData)(nil), "babylon.zoneconcierge.v1.FinalizedBSNData")
	proto.RegisterType((*QueryLatestEpochHeaderRequest)(nil), "babylon.zoneconcierge.v1.QueryLatestEpochHeaderRequest")
	proto.RegisterType((*QueryLatestEpochHeaderResponse)(nil), "babylon.zoneconcierge.v1.QueryLatestEpochHeaderResponse")
}

func init() {
	proto.RegisterFile("babylon/zoneconcierge/v1/query.proto", fileDescriptor_cd665af90102da38)
}

var fileDescriptor_cd665af90102da38 = []byte{
	// 735 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x8d, 0xfb, 0x13, 0x7d, 0x9d, 0x7c, 0xa0, 0x76, 0x5a, 0x44, 0x14, 0x41, 0x1a, 0x2c, 0x10,
	0x01, 0xb5, 0xb6, 0x92, 0x0a, 0xf1, 0x27, 0x7e, 0x94, 0x16, 0x44, 0x05, 0xaa, 0xc0, 0xa5, 0x12,
	0xea, 0xc6, 0x1a, 0x3b, 0x93, 0xc4, 0x6a, 0x32, 0xe3, 0x7a, 0x26, 0x69, 0x53, 0x60, 0xc3, 0x0b,
	0x80, 0xc4, 0x43, 0xf0, 0x12, 0xb0, 0xaf, 0xc4, 0xa6, 0x12, 0x1b, 0x56, 0x08, 0xb5, 0x3c, 0x08,
	0xf2, 0x78, 0xec, 0xc4, 0x0e, 0x26, 0x74, 0xe7, 0xdc, 0x39, 0xf7, 0xdc, 0x73, 0xef, 0x9c, 0x3b,
	0x01, 0x97, 0x2d, 0x64, 0xf5, 0xdb, 0x94, 0xe8, 0x07, 0x94, 0x60, 0x9b, 0x12, 0xdb, 0xc1, 0x5e,
	0x13, 0xeb, 0xbd, 0x8a, 0xbe, 0xdb, 0xc5, 0x5e, 0x5f, 0x73, 0x3d, 0xca, 0x29, 0xcc, 0x4b, 0x94,
	0x16, 0x43, 0x69, 0xbd, 0x4a, 0x61, 0xa1, 0x49, 0x9b, 0x54, 0x80, 0x74, 0xff, 0x2b, 0xc0, 0x17,
	0x2e, 0x34, 0x29, 0x6d, 0xb6, 0xb1, 0x8e, 0x5c, 0x47, 0x47, 0x84, 0x50, 0x8e, 0xb8, 0x43, 0x09,
	0x93, 0xa7, 0x4b, 0x61, 0x4d, 0x8b, 0xdb, 0x76, 0x0b, 0xdb, 0x3b, 0x2e, 0x75, 0x08, 0xf7, 0x6b,
	0xc6, 0x02, 0x12, 0x7d, 0x2d, 0x44, 0x0f, 0x4e, 0x1c, 0xd2, 0xf4, 0xd1, 0x23, 0x50, 0x35, 0x84,
	0x62, 0x97, 0xda, 0x2d, 0x89, 0x0a, 0xbf, 0x93, 0xc5, 0x47, 0x1a, 0x8e, 0xf7, 0x16, 0xa0, 0xaf,
	0xa4, 0xa2, 0x5d, 0xe4, 0xa1, 0x8e, 0xec, 0x48, 0x5d, 0x00, 0xf0, 0x85, 0x3f, 0xae, 0xe7, 0x22,
	0x68, 0xe0, 0xdd, 0x2e, 0x66, 0x5c, 0xdd, 0x02, 0xf3, 0xb1, 0x28, 0x73, 0x29, 0x61, 0x18, 0xde,
	0x07, 0xd9, 0x20, 0x39, 0xaf, 0x94, 0x94, 0x72, 0xae, 0x5a, 0xd2, 0xd2, 0xa6, 0xab, 0x05, 0x99,
	0xb5, 0xa9, 0xc3, 0x1f, 0x8b, 0x19, 0x43, 0x66, 0xa9, 0xaf, 0xc0, 0x45, 0x41, 0xfb, 0xd8, 0x21,
	0xa8, 0xed, 0x1c, 0xe0, 0x7a, 0x6d, 0x73, 0x83, 0xad, 0x93, 0x06, 0x95, 0x75, 0xe1, 0x25, 0xf0,
	0xbf, 0x4d, 0x09, 0xeb, 0x76, 0xb0, 0x67, 0x3a, 0x75, 0xbf, 0xcc, 0x64, 0x79, 0xc6, 0xc8, 0x85,
	0xb1, 0xf5, 0x3a, 0x83, 0x0b, 0x60, 0xda, 0xf5, 0x68, 0x0f, 0xe7, 0x27, 0x4a, 0x4a, 0xf9, 0x3f,
	0x23, 0xf8, 0xa1, 0xbe, 0x01, 0xc5, 0x34, 0x66, 0xa9, 0x7d, 0x1b, 0xcc, 0x37, 0xc2, 0x43, 0xd3,
	0x62, 0x84, 0x99, 0x75, 0xc4, 0x91, 0xa8, 0x90, 0xab, 0x5e, 0x4f, 0x6f, 0x64, 0x98, 0x71, 0x0d,
	0x71, 0x64, 0xcc, 0x45, 0x34, 0x35, 0x46, 0x98, 0x1f, 0x52, 0x3f, 0x4f, 0x82, 0xd9, 0x24, 0x0e,
	0x2e, 0x82, 0xdc, 0x50, 0x2f, 0x62, 0x62, 0x33, 0x06, 0x18, 0xb4, 0x02, 0x4d, 0x70, 0xbe, 0x8d,
	0x38, 0x66, 0xdc, 0x1c, 0x08, 0x6b, 0x61, 0x54, 0xc7, 0x9e, 0xe8, 0x2d, 0x57, 0xbd, 0x9a, 0xae,
	0x6a, 0x9d, 0xd4, 0xf1, 0x3e, 0xae, 0x3f, 0x11, 0x70, 0xe3, 0x5c, 0xc0, 0x13, 0x49, 0x08, 0xc2,
	0xf0, 0x36, 0x00, 0xc2, 0x42, 0xa6, 0x43, 0x1a, 0x34, 0x3f, 0x29, 0x38, 0x0b, 0x11, 0x67, 0xe4,
	0xae, 0x5e, 0x45, 0x7b, 0xe4, 0x7f, 0x1b, 0x33, 0x22, 0xe4, 0x4f, 0x0d, 0x6e, 0x80, 0xb3, 0x1e,
	0xda, 0x33, 0x07, 0x3e, 0xcd, 0x4f, 0x25, 0x24, 0xc5, 0x3c, 0xed, 0x73, 0x18, 0x68, 0x6f, 0x35,
	0x8a, 0x19, 0x67, 0xbc, 0xe1, 0x9f, 0x70, 0x0b, 0x40, 0x8b, 0xdb, 0x26, 0xeb, 0x5a, 0x1d, 0x87,
	0x31, 0x87, 0x12, 0x73, 0x07, 0xf7, 0xf3, 0xd3, 0x09, 0xce, 0xf8, 0x12, 0xf5, 0x2a, 0xda, 0x66,
	0x84, 0x7f, 0x8a, 0xfb, 0xc6, 0xac, 0xc5, 0xed, 0x58, 0x04, 0xae, 0x09, 0x33, 0xd0, 0x46, 0x3e,
	0x2b, 0x98, 0xb4, 0xbf, 0xf8, 0xd1, 0x87, 0x25, 0x06, 0x64, 0x04, 0xc9, 0xea, 0x43, 0x69, 0xcb,
	0x67, 0x62, 0x8a, 0x62, 0x16, 0x12, 0x20, 0x6d, 0x39, 0xee, 0x2a, 0x55, 0x24, 0xed, 0xf7, 0x07,
	0x06, 0x69, 0xbf, 0x07, 0x20, 0x2b, 0xef, 0x56, 0x39, 0xdd, 0xdd, 0xca, 0xb4, 0xea, 0xa7, 0x29,
	0x30, 0x2d, 0x6a, 0xc0, 0xf7, 0x0a, 0xc8, 0x06, 0xeb, 0x05, 0x97, 0xd2, 0x59, 0x46, 0xb7, 0xba,
	0xb0, 0xfc, 0x8f, 0xe8, 0x40, 0xb2, 0x5a, 0x7e, 0xf7, 0xed, 0xd7, 0xc7, 0x09, 0x15, 0x96, 0xf4,
	0x31, 0x4f, 0x09, 0xfc, 0xa2, 0x80, 0xb9, 0x91, 0xcd, 0x83, 0x37, 0xc7, 0x94, 0x4b, 0x7b, 0x05,
	0x0a, 0xb7, 0x4e, 0x9f, 0x28, 0x25, 0xdf, 0x10, 0x92, 0x75, 0xb8, 0x9c, 0x2e, 0x39, 0xf1, 0x08,
	0xf8, 0xab, 0x01, 0xbf, 0x2a, 0x60, 0x6e, 0xe4, 0xea, 0xc6, 0xea, 0x4f, 0xb3, 0xcb, 0x58, 0xfd,
	0xa9, 0x2e, 0x51, 0x57, 0x85, 0xfe, 0x7b, 0xf0, 0x6e, 0xba, 0x7e, 0xf9, 0x64, 0x04, 0x8b, 0x1d,
	0x78, 0x43, 0x7f, 0x3d, 0xe4, 0xce, 0xb7, 0xb5, 0x97, 0x87, 0xc7, 0x45, 0xe5, 0xe8, 0xb8, 0xa8,
	0xfc, 0x3c, 0x2e, 0x2a, 0x1f, 0x4e, 0x8a, 0x99, 0xa3, 0x93, 0x62, 0xe6, 0xfb, 0x49, 0x31, 0xb3,
	0x7d, 0xa7, 0xe9, 0xf0, 0x56, 0xd7, 0xd2, 0x6c, 0xda, 0x09, 0x0b, 0xb4, 0x91, 0xc5, 0x96, 0x1d,
	0x1a, 0xd5, 0xeb, 0xad, 0xe8, 0xfb, 0x89, 0xa2, 0xbc, 0xef, 0x62, 0x66, 0x65, 0xc5, 0xff, 0xc5,
	0xca, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xab, 0xa9, 0xea, 0x77, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// FinalizedBSNsInfo queries the BTC-finalised info of BSNs with given IDs, with proofs
	FinalizedBSNsInfo(ctx context.Context, in *QueryFinalizedBSNsInfoRequest, opts ...grpc.CallOption) (*QueryFinalizedBSNsInfoResponse, error)
	// LatestEpochHeader queries the latest epoch header for a given consumer ID
	LatestEpochHeader(ctx context.Context, in *QueryLatestEpochHeaderRequest, opts ...grpc.CallOption) (*QueryLatestEpochHeaderResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/babylon.zoneconcierge.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FinalizedBSNsInfo(ctx context.Context, in *QueryFinalizedBSNsInfoRequest, opts ...grpc.CallOption) (*QueryFinalizedBSNsInfoResponse, error) {
	out := new(QueryFinalizedBSNsInfoResponse)
	err := c.cc.Invoke(ctx, "/babylon.zoneconcierge.v1.Query/FinalizedBSNsInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestEpochHeader(ctx context.Context, in *QueryLatestEpochHeaderRequest, opts ...grpc.CallOption) (*QueryLatestEpochHeaderResponse, error) {
	out := new(QueryLatestEpochHeaderResponse)
	err := c.cc.Invoke(ctx, "/babylon.zoneconcierge.v1.Query/LatestEpochHeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// FinalizedBSNsInfo queries the BTC-finalised info of BSNs with given IDs, with proofs
	FinalizedBSNsInfo(context.Context, *QueryFinalizedBSNsInfoRequest) (*QueryFinalizedBSNsInfoResponse, error)
	// LatestEpochHeader queries the latest epoch header for a given consumer ID
	LatestEpochHeader(context.Context, *QueryLatestEpochHeaderRequest) (*QueryLatestEpochHeaderResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) FinalizedBSNsInfo(ctx context.Context, req *QueryFinalizedBSNsInfoRequest) (*QueryFinalizedBSNsInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizedBSNsInfo not implemented")
}
func (*UnimplementedQueryServer) LatestEpochHeader(ctx context.Context, req *QueryLatestEpochHeaderRequest) (*QueryLatestEpochHeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestEpochHeader not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/babylon.zoneconcierge.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FinalizedBSNsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFinalizedBSNsInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FinalizedBSNsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/babylon.zoneconcierge.v1.Query/FinalizedBSNsInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FinalizedBSNsInfo(ctx, req.(*QueryFinalizedBSNsInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestEpochHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestEpochHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestEpochHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/babylon.zoneconcierge.v1.Query/LatestEpochHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestEpochHeader(ctx, req.(*QueryLatestEpochHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "babylon.zoneconcierge.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "FinalizedBSNsInfo",
			Handler:    _Query_FinalizedBSNsInfo_Handler,
		},
		{
			MethodName: "LatestEpochHeader",
			Handler:    _Query_LatestEpochHeader_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "babylon/zoneconcierge/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryFinalizedBSNsInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFinalizedBSNsInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFinalizedBSNsInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Prove {
		i--
		if m.Prove {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.ConsumerIds) > 0 {
		for iNdEx := len(m.ConsumerIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ConsumerIds[iNdEx])
			copy(dAtA[i:], m.ConsumerIds[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.ConsumerIds[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryFinalizedBSNsInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFinalizedBSNsInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFinalizedBSNsInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FinalizedBsnsData) > 0 {
		for iNdEx := len(m.FinalizedBsnsData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FinalizedBsnsData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *FinalizedBSNData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FinalizedBSNData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FinalizedBSNData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Proof != nil {
		{
			size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.BtcSubmissionKey != nil {
		{
			size, err := m.BtcSubmissionKey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.RawCheckpoint != nil {
		{
			size, err := m.RawCheckpoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.EpochInfo != nil {
		{
			size, err := m.EpochInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.LatestFinalizedHeader != nil {
		{
			size, err := m.LatestFinalizedHeader.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ConsumerId) > 0 {
		i -= len(m.ConsumerId)
		copy(dAtA[i:], m.ConsumerId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ConsumerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLatestEpochHeaderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestEpochHeaderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestEpochHeaderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConsumerId) > 0 {
		i -= len(m.ConsumerId)
		copy(dAtA[i:], m.ConsumerId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ConsumerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLatestEpochHeaderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestEpochHeaderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestEpochHeaderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Header != nil {
		{
			size, err := m.Header.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryFinalizedBSNsInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ConsumerIds) > 0 {
		for _, s := range m.ConsumerIds {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Prove {
		n += 2
	}
	return n
}

func (m *QueryFinalizedBSNsInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.FinalizedBsnsData) > 0 {
		for _, e := range m.FinalizedBsnsData {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *FinalizedBSNData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConsumerId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.LatestFinalizedHeader != nil {
		l = m.LatestFinalizedHeader.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.EpochInfo != nil {
		l = m.EpochInfo.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.RawCheckpoint != nil {
		l = m.RawCheckpoint.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.BtcSubmissionKey != nil {
		l = m.BtcSubmissionKey.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Proof != nil {
		l = m.Proof.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLatestEpochHeaderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConsumerId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLatestEpochHeaderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFinalizedBSNsInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFinalizedBSNsInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFinalizedBSNsInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerIds = append(m.ConsumerIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prove", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Prove = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFinalizedBSNsInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFinalizedBSNsInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFinalizedBSNsInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedBsnsData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalizedBsnsData = append(m.FinalizedBsnsData, &FinalizedBSNData{})
			if err := m.FinalizedBsnsData[len(m.FinalizedBsnsData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FinalizedBSNData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FinalizedBSNData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FinalizedBSNData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestFinalizedHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LatestFinalizedHeader == nil {
				m.LatestFinalizedHeader = &IndexedHeader{}
			}
			if err := m.LatestFinalizedHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EpochInfo == nil {
				m.EpochInfo = &types.Epoch{}
			}
			if err := m.EpochInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawCheckpoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RawCheckpoint == nil {
				m.RawCheckpoint = &types1.RawCheckpoint{}
			}
			if err := m.RawCheckpoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcSubmissionKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BtcSubmissionKey == nil {
				m.BtcSubmissionKey = &types2.SubmissionKey{}
			}
			if err := m.BtcSubmissionKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proof == nil {
				m.Proof = &ProofFinalizedHeader{}
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestEpochHeaderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestEpochHeaderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestEpochHeaderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestEpochHeaderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestEpochHeaderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestEpochHeaderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &IndexedHeader{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
