// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babylon/zoneconcierge/v1/zoneconcierge.proto

package types

import (
	fmt "fmt"
	types2 "github.com/babylonchain/babylon/x/btccheckpoint/types"
	types3 "github.com/babylonchain/babylon/x/btclightclient/types"
	types1 "github.com/babylonchain/babylon/x/checkpointing/types"
	types "github.com/babylonchain/babylon/x/epoching/types"
	crypto "github.com/cometbft/cometbft/proto/tendermint/crypto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// IndexedHeader is the metadata of a CZ header
type IndexedHeader struct {
	// chain_id is the unique ID of the chain
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// hash is the hash of this header
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// height is the height of this header on CZ ledger
	// (hash, height) jointly provides the position of the header on CZ ledger
	Height uint64 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// time is the timestamp of this header on CZ ledger
	// it is needed for CZ to unbond all mature validators/delegations
	// before this timestamp when this header is BTC-finalised
	Time *time.Time `protobuf:"bytes,4,opt,name=time,proto3,stdtime" json:"time,omitempty"`
	// babylon_header_hash is the hash of the babylon block that includes this CZ
	// header
	BabylonHeaderHash []byte `protobuf:"bytes,5,opt,name=babylon_header_hash,json=babylonHeaderHash,proto3" json:"babylon_header_hash,omitempty"`
	// babylon_header_height is the height of the babylon block that includes this CZ
	// header
	BabylonHeaderHeight uint64 `protobuf:"varint,6,opt,name=babylon_header_height,json=babylonHeaderHeight,proto3" json:"babylon_header_height,omitempty"`
	// epoch is the epoch number of this header on Babylon ledger
	BabylonEpoch uint64 `protobuf:"varint,7,opt,name=babylon_epoch,json=babylonEpoch,proto3" json:"babylon_epoch,omitempty"`
	// babylon_tx_hash is the hash of the tx that includes this header
	// (babylon_block_height, babylon_tx_hash) jointly provides the position of
	// the header on Babylon ledger
	BabylonTxHash []byte `protobuf:"bytes,8,opt,name=babylon_tx_hash,json=babylonTxHash,proto3" json:"babylon_tx_hash,omitempty"`
}

func (m *IndexedHeader) Reset()         { *m = IndexedHeader{} }
func (m *IndexedHeader) String() string { return proto.CompactTextString(m) }
func (*IndexedHeader) ProtoMessage()    {}
func (*IndexedHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab886e1868e5c5cd, []int{0}
}
func (m *IndexedHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IndexedHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IndexedHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IndexedHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexedHeader.Merge(m, src)
}
func (m *IndexedHeader) XXX_Size() int {
	return m.Size()
}
func (m *IndexedHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexedHeader.DiscardUnknown(m)
}

var xxx_messageInfo_IndexedHeader proto.InternalMessageInfo

func (m *IndexedHeader) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *IndexedHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *IndexedHeader) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *IndexedHeader) GetTime() *time.Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *IndexedHeader) GetBabylonHeaderHash() []byte {
	if m != nil {
		return m.BabylonHeaderHash
	}
	return nil
}

func (m *IndexedHeader) GetBabylonHeaderHeight() uint64 {
	if m != nil {
		return m.BabylonHeaderHeight
	}
	return 0
}

func (m *IndexedHeader) GetBabylonEpoch() uint64 {
	if m != nil {
		return m.BabylonEpoch
	}
	return 0
}

func (m *IndexedHeader) GetBabylonTxHash() []byte {
	if m != nil {
		return m.BabylonTxHash
	}
	return nil
}

// Forks is a list of non-canonical `IndexedHeader`s at the same height.
// For example, assuming the following blockchain
// ```
// A <- B <- C <- D <- E
//
//	\ -- D1
//	\ -- D2
//
// ```
// Then the fork will be {[D1, D2]} where each item is in struct `IndexedBlock`.
//
// Note that each `IndexedHeader` in the fork should have a valid quorum
// certificate. Such forks exist since Babylon considers CZs might have
// dishonest majority. Also note that the IBC-Go implementation will only
// consider the first header in a fork valid, since the subsequent headers
// cannot be verified without knowing the validator set in the previous header.
type Forks struct {
	// blocks is the list of non-canonical indexed headers at the same height
	Headers []*IndexedHeader `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
}

func (m *Forks) Reset()         { *m = Forks{} }
func (m *Forks) String() string { return proto.CompactTextString(m) }
func (*Forks) ProtoMessage()    {}
func (*Forks) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab886e1868e5c5cd, []int{1}
}
func (m *Forks) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Forks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Forks.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Forks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Forks.Merge(m, src)
}
func (m *Forks) XXX_Size() int {
	return m.Size()
}
func (m *Forks) XXX_DiscardUnknown() {
	xxx_messageInfo_Forks.DiscardUnknown(m)
}

var xxx_messageInfo_Forks proto.InternalMessageInfo

func (m *Forks) GetHeaders() []*IndexedHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

// ChainInfo is the information of a CZ
type ChainInfo struct {
	// chain_id is the ID of the chain
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// latest_header is the latest header in CZ's canonical chain
	LatestHeader *IndexedHeader `protobuf:"bytes,2,opt,name=latest_header,json=latestHeader,proto3" json:"latest_header,omitempty"`
	// latest_forks is the latest forks, formed as a series of IndexedHeader (from
	// low to high)
	LatestForks *Forks `protobuf:"bytes,3,opt,name=latest_forks,json=latestForks,proto3" json:"latest_forks,omitempty"`
	// timestamped_headers_count is the number of timestamped headers in CZ's
	// canonical chain
	TimestampedHeadersCount uint64 `protobuf:"varint,4,opt,name=timestamped_headers_count,json=timestampedHeadersCount,proto3" json:"timestamped_headers_count,omitempty"`
}

func (m *ChainInfo) Reset()         { *m = ChainInfo{} }
func (m *ChainInfo) String() string { return proto.CompactTextString(m) }
func (*ChainInfo) ProtoMessage()    {}
func (*ChainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab886e1868e5c5cd, []int{2}
}
func (m *ChainInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainInfo.Merge(m, src)
}
func (m *ChainInfo) XXX_Size() int {
	return m.Size()
}
func (m *ChainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChainInfo proto.InternalMessageInfo

func (m *ChainInfo) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *ChainInfo) GetLatestHeader() *IndexedHeader {
	if m != nil {
		return m.LatestHeader
	}
	return nil
}

func (m *ChainInfo) GetLatestForks() *Forks {
	if m != nil {
		return m.LatestForks
	}
	return nil
}

func (m *ChainInfo) GetTimestampedHeadersCount() uint64 {
	if m != nil {
		return m.TimestampedHeadersCount
	}
	return 0
}

// ChainRegister is the registration information of a CZ
type ChainRegister struct {
	// chain_id is the ID of the chain
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// chain_name is the name of the chain
	ChainName string `protobuf:"bytes,2,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	// chain_description is a description for the chain (can be empty)
	ChainDescription string `protobuf:"bytes,3,opt,name=chain_description,json=chainDescription,proto3" json:"chain_description,omitempty"`
}

func (m *ChainRegister) Reset()         { *m = ChainRegister{} }
func (m *ChainRegister) String() string { return proto.CompactTextString(m) }
func (*ChainRegister) ProtoMessage()    {}
func (*ChainRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab886e1868e5c5cd, []int{3}
}
func (m *ChainRegister) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainRegister.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainRegister.Merge(m, src)
}
func (m *ChainRegister) XXX_Size() int {
	return m.Size()
}
func (m *ChainRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ChainRegister proto.InternalMessageInfo

func (m *ChainRegister) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *ChainRegister) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *ChainRegister) GetChainDescription() string {
	if m != nil {
		return m.ChainDescription
	}
	return ""
}

// FinalizedChainInfo is the information of a CZ that is BTC-finalised
type FinalizedChainInfo struct {
	// chain_id is the ID of the chain
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// finalized_chain_info is the info of the CZ
	FinalizedChainInfo *ChainInfo `protobuf:"bytes,2,opt,name=finalized_chain_info,json=finalizedChainInfo,proto3" json:"finalized_chain_info,omitempty"`
	// epoch_info is the metadata of the last BTC-finalised epoch
	EpochInfo *types.Epoch `protobuf:"bytes,3,opt,name=epoch_info,json=epochInfo,proto3" json:"epoch_info,omitempty"`
	// raw_checkpoint is the raw checkpoint of this epoch
	RawCheckpoint *types1.RawCheckpoint `protobuf:"bytes,4,opt,name=raw_checkpoint,json=rawCheckpoint,proto3" json:"raw_checkpoint,omitempty"`
	// btc_submission_key is position of two BTC txs that include the raw
	// checkpoint of this epoch
	BtcSubmissionKey *types2.SubmissionKey `protobuf:"bytes,5,opt,name=btc_submission_key,json=btcSubmissionKey,proto3" json:"btc_submission_key,omitempty"`
	// proof is the proof that the chain info is finalized
	Proof *ProofFinalizedChainInfo `protobuf:"bytes,6,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *FinalizedChainInfo) Reset()         { *m = FinalizedChainInfo{} }
func (m *FinalizedChainInfo) String() string { return proto.CompactTextString(m) }
func (*FinalizedChainInfo) ProtoMessage()    {}
func (*FinalizedChainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab886e1868e5c5cd, []int{4}
}
func (m *FinalizedChainInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FinalizedChainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FinalizedChainInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FinalizedChainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizedChainInfo.Merge(m, src)
}
func (m *FinalizedChainInfo) XXX_Size() int {
	return m.Size()
}
func (m *FinalizedChainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizedChainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizedChainInfo proto.InternalMessageInfo

func (m *FinalizedChainInfo) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *FinalizedChainInfo) GetFinalizedChainInfo() *ChainInfo {
	if m != nil {
		return m.FinalizedChainInfo
	}
	return nil
}

func (m *FinalizedChainInfo) GetEpochInfo() *types.Epoch {
	if m != nil {
		return m.EpochInfo
	}
	return nil
}

func (m *FinalizedChainInfo) GetRawCheckpoint() *types1.RawCheckpoint {
	if m != nil {
		return m.RawCheckpoint
	}
	return nil
}

func (m *FinalizedChainInfo) GetBtcSubmissionKey() *types2.SubmissionKey {
	if m != nil {
		return m.BtcSubmissionKey
	}
	return nil
}

func (m *FinalizedChainInfo) GetProof() *ProofFinalizedChainInfo {
	if m != nil {
		return m.Proof
	}
	return nil
}

// ProofEpochSealed is the proof that an epoch is sealed by the sealer header,
// i.e., the 2nd header of the next epoch With the access of metadata
// - Metadata of this epoch, which includes the sealer header
// - Raw checkpoint of this epoch
// The verifier can perform the following verification rules:
// - The raw checkpoint's `app_hash` is same as in the sealer header
// - More than 2/3 (in voting power) validators in the validator set of this
// epoch have signed `app_hash` of the sealer header
// - The epoch metadata is committed to the `app_hash` of the sealer header
// - The validator set is committed to the `app_hash` of the sealer header
type ProofEpochSealed struct {
	// validator_set is the validator set of the sealed epoch
	// This validator set has generated a BLS multisig on `app_hash` of
	// the sealer header
	ValidatorSet []*types1.ValidatorWithBlsKey `protobuf:"bytes,1,rep,name=validator_set,json=validatorSet,proto3" json:"validator_set,omitempty"`
	// proof_epoch_info is the Merkle proof that the epoch's metadata is committed
	// to `app_hash` of the sealer header
	ProofEpochInfo *crypto.ProofOps `protobuf:"bytes,2,opt,name=proof_epoch_info,json=proofEpochInfo,proto3" json:"proof_epoch_info,omitempty"`
	// proof_epoch_info is the Merkle proof that the epoch's validator set is
	// committed to `app_hash` of the sealer header
	ProofEpochValSet *crypto.ProofOps `protobuf:"bytes,3,opt,name=proof_epoch_val_set,json=proofEpochValSet,proto3" json:"proof_epoch_val_set,omitempty"`
}

func (m *ProofEpochSealed) Reset()         { *m = ProofEpochSealed{} }
func (m *ProofEpochSealed) String() string { return proto.CompactTextString(m) }
func (*ProofEpochSealed) ProtoMessage()    {}
func (*ProofEpochSealed) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab886e1868e5c5cd, []int{5}
}
func (m *ProofEpochSealed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProofEpochSealed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProofEpochSealed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProofEpochSealed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofEpochSealed.Merge(m, src)
}
func (m *ProofEpochSealed) XXX_Size() int {
	return m.Size()
}
func (m *ProofEpochSealed) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofEpochSealed.DiscardUnknown(m)
}

var xxx_messageInfo_ProofEpochSealed proto.InternalMessageInfo

func (m *ProofEpochSealed) GetValidatorSet() []*types1.ValidatorWithBlsKey {
	if m != nil {
		return m.ValidatorSet
	}
	return nil
}

func (m *ProofEpochSealed) GetProofEpochInfo() *crypto.ProofOps {
	if m != nil {
		return m.ProofEpochInfo
	}
	return nil
}

func (m *ProofEpochSealed) GetProofEpochValSet() *crypto.ProofOps {
	if m != nil {
		return m.ProofEpochValSet
	}
	return nil
}

// ProofFinalizedChainInfo is a set of proofs that attest a chain info is
// BTC-finalised
type ProofFinalizedChainInfo struct {
	// proof_cz_header_in_epoch is the proof that the CZ header is timestamped
	// within a certain epoch
	ProofCzHeaderInEpoch *crypto.ProofOps `protobuf:"bytes,1,opt,name=proof_cz_header_in_epoch,json=proofCzHeaderInEpoch,proto3" json:"proof_cz_header_in_epoch,omitempty"`
	// proof_epoch_sealed is the proof that the epoch is sealed
	ProofEpochSealed *ProofEpochSealed `protobuf:"bytes,2,opt,name=proof_epoch_sealed,json=proofEpochSealed,proto3" json:"proof_epoch_sealed,omitempty"`
	// proof_epoch_submitted is the proof that the epoch's checkpoint is included
	// in BTC ledger It is the two TransactionInfo in the best (i.e., earliest)
	// checkpoint submission
	ProofEpochSubmitted []*types2.TransactionInfo `protobuf:"bytes,3,rep,name=proof_epoch_submitted,json=proofEpochSubmitted,proto3" json:"proof_epoch_submitted,omitempty"`
}

func (m *ProofFinalizedChainInfo) Reset()         { *m = ProofFinalizedChainInfo{} }
func (m *ProofFinalizedChainInfo) String() string { return proto.CompactTextString(m) }
func (*ProofFinalizedChainInfo) ProtoMessage()    {}
func (*ProofFinalizedChainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab886e1868e5c5cd, []int{6}
}
func (m *ProofFinalizedChainInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProofFinalizedChainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProofFinalizedChainInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProofFinalizedChainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofFinalizedChainInfo.Merge(m, src)
}
func (m *ProofFinalizedChainInfo) XXX_Size() int {
	return m.Size()
}
func (m *ProofFinalizedChainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofFinalizedChainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProofFinalizedChainInfo proto.InternalMessageInfo

func (m *ProofFinalizedChainInfo) GetProofCzHeaderInEpoch() *crypto.ProofOps {
	if m != nil {
		return m.ProofCzHeaderInEpoch
	}
	return nil
}

func (m *ProofFinalizedChainInfo) GetProofEpochSealed() *ProofEpochSealed {
	if m != nil {
		return m.ProofEpochSealed
	}
	return nil
}

func (m *ProofFinalizedChainInfo) GetProofEpochSubmitted() []*types2.TransactionInfo {
	if m != nil {
		return m.ProofEpochSubmitted
	}
	return nil
}

// Btc light client chain segment grown during last finalized epoch
type BTCChainSegment struct {
	BtcHeaders []*types3.BTCHeaderInfo `protobuf:"bytes,1,rep,name=btc_headers,json=btcHeaders,proto3" json:"btc_headers,omitempty"`
}

func (m *BTCChainSegment) Reset()         { *m = BTCChainSegment{} }
func (m *BTCChainSegment) String() string { return proto.CompactTextString(m) }
func (*BTCChainSegment) ProtoMessage()    {}
func (*BTCChainSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab886e1868e5c5cd, []int{7}
}
func (m *BTCChainSegment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BTCChainSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BTCChainSegment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BTCChainSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BTCChainSegment.Merge(m, src)
}
func (m *BTCChainSegment) XXX_Size() int {
	return m.Size()
}
func (m *BTCChainSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_BTCChainSegment.DiscardUnknown(m)
}

var xxx_messageInfo_BTCChainSegment proto.InternalMessageInfo

func (m *BTCChainSegment) GetBtcHeaders() []*types3.BTCHeaderInfo {
	if m != nil {
		return m.BtcHeaders
	}
	return nil
}

func init() {
	proto.RegisterType((*IndexedHeader)(nil), "babylon.zoneconcierge.v1.IndexedHeader")
	proto.RegisterType((*Forks)(nil), "babylon.zoneconcierge.v1.Forks")
	proto.RegisterType((*ChainInfo)(nil), "babylon.zoneconcierge.v1.ChainInfo")
	proto.RegisterType((*ChainRegister)(nil), "babylon.zoneconcierge.v1.ChainRegister")
	proto.RegisterType((*FinalizedChainInfo)(nil), "babylon.zoneconcierge.v1.FinalizedChainInfo")
	proto.RegisterType((*ProofEpochSealed)(nil), "babylon.zoneconcierge.v1.ProofEpochSealed")
	proto.RegisterType((*ProofFinalizedChainInfo)(nil), "babylon.zoneconcierge.v1.ProofFinalizedChainInfo")
	proto.RegisterType((*BTCChainSegment)(nil), "babylon.zoneconcierge.v1.BTCChainSegment")
}

func init() {
	proto.RegisterFile("babylon/zoneconcierge/v1/zoneconcierge.proto", fileDescriptor_ab886e1868e5c5cd)
}

var fileDescriptor_ab886e1868e5c5cd = []byte{
	// 977 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0x2d, 0xd9, 0x8e, 0x46, 0x56, 0xa2, 0xac, 0x9d, 0x46, 0x71, 0x11, 0x59, 0x50, 0x80,
	0x54, 0xe9, 0x0f, 0x05, 0xa9, 0xed, 0xa1, 0xbd, 0x55, 0x6a, 0xd2, 0x38, 0x2d, 0x92, 0x62, 0xa5,
	0xa4, 0x45, 0xd1, 0x82, 0xe0, 0xcf, 0x8a, 0x24, 0x4c, 0x71, 0x05, 0xee, 0x5a, 0xb1, 0xfc, 0x14,
	0x79, 0x8b, 0x9e, 0xfb, 0x00, 0xbd, 0xf7, 0x98, 0x63, 0x6f, 0x2d, 0xec, 0x57, 0xe8, 0xa5, 0xb7,
	0x82, 0xb3, 0x4b, 0x89, 0x8c, 0xa1, 0xb8, 0xb9, 0x18, 0xda, 0xd9, 0x6f, 0x66, 0xbe, 0xfd, 0xe6,
	0x87, 0x86, 0x8f, 0x1d, 0xdb, 0x59, 0x44, 0x3c, 0xee, 0x9e, 0xf1, 0x98, 0xb9, 0x3c, 0x76, 0x43,
	0x96, 0xf8, 0xac, 0x3b, 0xef, 0x15, 0x0d, 0xe6, 0x2c, 0xe1, 0x92, 0x93, 0x86, 0x46, 0x9b, 0xc5,
	0xcb, 0x79, 0xef, 0x60, 0xdf, 0xe7, 0x3e, 0x47, 0x50, 0x37, 0xfd, 0xa5, 0xf0, 0x07, 0x87, 0x3e,
	0xe7, 0x7e, 0xc4, 0xba, 0x78, 0x72, 0x4e, 0x26, 0x5d, 0x19, 0x4e, 0x99, 0x90, 0xf6, 0x74, 0xa6,
	0x01, 0x77, 0x25, 0x8b, 0x3d, 0x96, 0x4c, 0xc3, 0x58, 0x76, 0xdd, 0x64, 0x31, 0x93, 0x3c, 0xc5,
	0xf2, 0x89, 0xbe, 0x5e, 0xb2, 0x73, 0xa4, 0xeb, 0x06, 0xcc, 0x3d, 0x9e, 0xf1, 0x14, 0x39, 0xef,
	0x15, 0x0d, 0x1a, 0x7d, 0x3f, 0x43, 0xaf, 0x6e, 0xc2, 0xd8, 0x47, 0x74, 0x24, 0xac, 0x63, 0xb6,
	0xd0, 0xb8, 0x07, 0x6b, 0x71, 0x97, 0x42, 0xb6, 0x33, 0x28, 0x9b, 0x71, 0x37, 0xd0, 0xa8, 0xec,
	0xb7, 0xc6, 0x98, 0x39, 0x92, 0x51, 0xe8, 0x07, 0xe9, 0x5f, 0xb6, 0x64, 0x99, 0xb3, 0x28, 0x7c,
	0xfb, 0xf7, 0x4d, 0xa8, 0x1d, 0xc5, 0x1e, 0x3b, 0x65, 0xde, 0x63, 0x66, 0x7b, 0x2c, 0x21, 0x77,
	0xe0, 0x9a, 0x1b, 0xd8, 0x61, 0x6c, 0x85, 0x5e, 0xc3, 0x68, 0x19, 0x9d, 0x0a, 0xdd, 0xc1, 0xf3,
	0x91, 0x47, 0x08, 0x94, 0x03, 0x5b, 0x04, 0x8d, 0xcd, 0x96, 0xd1, 0xd9, 0xa5, 0xf8, 0x9b, 0xbc,
	0x07, 0xdb, 0x01, 0x4b, 0xc3, 0x36, 0x4a, 0x2d, 0xa3, 0x53, 0xa6, 0xfa, 0x44, 0x3e, 0x83, 0x72,
	0xaa, 0x6f, 0xa3, 0xdc, 0x32, 0x3a, 0xd5, 0xfe, 0x81, 0xa9, 0xc4, 0x37, 0x33, 0xf1, 0xcd, 0x71,
	0x26, 0xfe, 0xa0, 0xfc, 0xea, 0xaf, 0x43, 0x83, 0x22, 0x9a, 0x98, 0xb0, 0xa7, 0x1f, 0x60, 0x05,
	0x48, 0xc7, 0xc2, 0x84, 0x5b, 0x98, 0xf0, 0xa6, 0xbe, 0x52, 0x44, 0x1f, 0xa7, 0xd9, 0xfb, 0x70,
	0xeb, 0x4d, 0xbc, 0x22, 0xb3, 0x8d, 0x64, 0xf6, 0x8a, 0x1e, 0x8a, 0xd9, 0x3d, 0xa8, 0x65, 0x3e,
	0x28, 0x5e, 0x63, 0x07, 0xb1, 0xbb, 0xda, 0xf8, 0x30, 0xb5, 0x91, 0xfb, 0x70, 0x23, 0x03, 0xc9,
	0x53, 0x45, 0xe2, 0x1a, 0x92, 0xc8, 0x7c, 0xc7, 0xa7, 0x29, 0x81, 0xf6, 0x13, 0xd8, 0x7a, 0xc4,
	0x93, 0x63, 0x41, 0xbe, 0x82, 0x1d, 0xc5, 0x40, 0x34, 0x4a, 0xad, 0x52, 0xa7, 0xda, 0xff, 0xc0,
	0x5c, 0xd7, 0x9f, 0x66, 0x41, 0x70, 0x9a, 0xf9, 0xb5, 0xff, 0x31, 0xa0, 0x32, 0x44, 0xa9, 0xe3,
	0x09, 0x7f, 0x5b, 0x1d, 0xbe, 0x83, 0x5a, 0x64, 0x4b, 0x26, 0xa4, 0x7e, 0x34, 0x16, 0xe4, 0x1d,
	0x32, 0xee, 0x2a, 0x6f, 0x5d, 0xf0, 0x01, 0xe8, 0xb3, 0x35, 0x49, 0x5f, 0x82, 0x75, 0xac, 0xf6,
	0x0f, 0xd7, 0x07, 0xc3, 0x07, 0xd3, 0xaa, 0x72, 0x52, 0xaf, 0xff, 0x12, 0xee, 0x2c, 0xa7, 0x89,
	0x79, 0x9a, 0x96, 0xb0, 0x5c, 0x7e, 0x12, 0x4b, 0x6c, 0x81, 0x32, 0xbd, 0x9d, 0x03, 0xa8, 0xcc,
	0x62, 0x98, 0x5e, 0xb7, 0xe7, 0x50, 0xc3, 0x57, 0x53, 0xe6, 0x87, 0x42, 0xbe, 0xbd, 0x03, 0xef,
	0x02, 0xa8, 0xab, 0xd8, 0x9e, 0x32, 0x7c, 0x76, 0x85, 0x56, 0xd0, 0xf2, 0xd4, 0x9e, 0x32, 0xf2,
	0x11, 0xdc, 0x54, 0xd7, 0x1e, 0x13, 0x6e, 0x12, 0xce, 0x64, 0xc8, 0x63, 0x7c, 0x4f, 0x85, 0xd6,
	0xf1, 0xe2, 0xeb, 0x95, 0xbd, 0xfd, 0x5b, 0x09, 0xc8, 0xa3, 0x30, 0xb6, 0xa3, 0xf0, 0x8c, 0x79,
	0xff, 0x4b, 0xf7, 0xe7, 0xb0, 0x3f, 0xc9, 0x1c, 0x2c, 0x0d, 0x8a, 0x27, 0x5c, 0xcb, 0x7f, 0x6f,
	0xbd, 0x62, 0xcb, 0xe8, 0x94, 0x4c, 0x2e, 0x67, 0xfc, 0x02, 0x00, 0x1b, 0x51, 0x05, 0x2b, 0xe9,
	0x81, 0xc9, 0x82, 0x2d, 0x07, 0x7c, 0xde, 0x33, 0xb1, 0x37, 0x69, 0x05, 0x4d, 0xe8, 0xfa, 0x14,
	0xae, 0x27, 0xf6, 0x4b, 0x6b, 0xb5, 0x2a, 0xf4, 0xbc, 0xad, 0x5a, 0xa1, 0xb0, 0x56, 0xd2, 0x18,
	0xd4, 0x7e, 0x39, 0x5c, 0xda, 0x68, 0x2d, 0xc9, 0x1f, 0xc9, 0x73, 0x20, 0x8e, 0x74, 0x2d, 0x71,
	0xe2, 0x4c, 0x43, 0x21, 0x42, 0x1e, 0xa7, 0x9b, 0x0a, 0xc7, 0x2f, 0x1f, 0xb3, 0xb8, 0xef, 0xe6,
	0x3d, 0x73, 0xb4, 0xc4, 0x7f, 0xcb, 0x16, 0xb4, 0xee, 0x48, 0xb7, 0x60, 0x21, 0xdf, 0xc0, 0x16,
	0x6e, 0x52, 0x1c, 0xcb, 0x6a, 0xbf, 0xb7, 0x5e, 0xa9, 0xef, 0x53, 0xd8, 0xe5, 0xaa, 0x50, 0xe5,
	0xdf, 0xfe, 0xd7, 0x80, 0x3a, 0x42, 0x50, 0x89, 0x11, 0xb3, 0x23, 0xe6, 0x11, 0x0a, 0xb5, 0xb9,
	0x1d, 0x85, 0x9e, 0x2d, 0x79, 0x62, 0x09, 0x26, 0x1b, 0x06, 0x0e, 0xe0, 0x27, 0xeb, 0x35, 0x78,
	0x91, 0xc1, 0x7f, 0x08, 0x65, 0x30, 0x88, 0x44, 0xca, 0x7a, 0x77, 0x19, 0x63, 0xc4, 0x24, 0x79,
	0x08, 0x75, 0xcc, 0x68, 0xe5, 0x2a, 0xa3, 0xca, 0xfc, 0xbe, 0xb9, 0xfa, 0x4c, 0x98, 0xea, 0x33,
	0xa1, 0x58, 0x3f, 0x9b, 0x09, 0x7a, 0x7d, 0xb6, 0x24, 0x87, 0xf5, 0x79, 0x02, 0x7b, 0xf9, 0x30,
	0x73, 0x3b, 0x42, 0x82, 0xa5, 0xab, 0x23, 0xd5, 0x57, 0x91, 0x5e, 0xd8, 0xd1, 0x88, 0xc9, 0xf6,
	0xaf, 0x9b, 0x70, 0x7b, 0x8d, 0x3c, 0x64, 0x04, 0x0d, 0x95, 0xc7, 0x3d, 0xcb, 0x16, 0x61, 0x98,
	0xad, 0x37, 0xe3, 0xea, 0x64, 0xfb, 0xe8, 0x3c, 0x3c, 0x53, 0x73, 0x79, 0xa4, 0x77, 0xe0, 0x8f,
	0x40, 0xf2, 0xe4, 0x05, 0xaa, 0xad, 0x55, 0xf8, 0xf0, 0x8a, 0x12, 0xe6, 0xea, 0x93, 0x7f, 0x8a,
	0xae, 0xd8, 0x2f, 0x70, 0xab, 0x10, 0x39, 0x6d, 0x16, 0x29, 0x99, 0xa7, 0x57, 0xe7, 0x83, 0xf5,
	0x9d, 0x36, 0x4e, 0xec, 0x58, 0xd8, 0x6e, 0x3a, 0xc0, 0xd8, 0x17, 0x7b, 0xb9, 0xd8, 0x59, 0x94,
	0xf6, 0xcf, 0x70, 0x63, 0x30, 0x1e, 0xa2, 0x3a, 0x23, 0xe6, 0x4f, 0x59, 0x2c, 0xc9, 0x11, 0x54,
	0xd3, 0xc6, 0xce, 0x56, 0xb4, 0xea, 0x90, 0x4e, 0x3e, 0x4f, 0xfe, 0xdb, 0x38, 0xef, 0x99, 0x83,
	0xf1, 0x30, 0x53, 0x63, 0xc2, 0x29, 0x38, 0xd2, 0xd5, 0x4b, 0x6b, 0xf0, 0xec, 0x8f, 0xf3, 0xa6,
	0xf1, 0xfa, 0xbc, 0x69, 0xfc, 0x7d, 0xde, 0x34, 0x5e, 0x5d, 0x34, 0x37, 0x5e, 0x5f, 0x34, 0x37,
	0xfe, 0xbc, 0x68, 0x6e, 0xfc, 0xf4, 0xb9, 0x1f, 0xca, 0xe0, 0xc4, 0x31, 0x5d, 0x3e, 0xed, 0xea,
	0xc8, 0xb8, 0x25, 0xb2, 0x43, 0xf7, 0xf4, 0x8d, 0xff, 0x6c, 0xe4, 0x62, 0xc6, 0x84, 0xb3, 0x8d,
	0x1f, 0xc5, 0x4f, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xe2, 0xb8, 0x3f, 0xff, 0x08, 0x00,
	0x00,
}

func (m *IndexedHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndexedHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IndexedHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BabylonTxHash) > 0 {
		i -= len(m.BabylonTxHash)
		copy(dAtA[i:], m.BabylonTxHash)
		i = encodeVarintZoneconcierge(dAtA, i, uint64(len(m.BabylonTxHash)))
		i--
		dAtA[i] = 0x42
	}
	if m.BabylonEpoch != 0 {
		i = encodeVarintZoneconcierge(dAtA, i, uint64(m.BabylonEpoch))
		i--
		dAtA[i] = 0x38
	}
	if m.BabylonHeaderHeight != 0 {
		i = encodeVarintZoneconcierge(dAtA, i, uint64(m.BabylonHeaderHeight))
		i--
		dAtA[i] = 0x30
	}
	if len(m.BabylonHeaderHash) > 0 {
		i -= len(m.BabylonHeaderHash)
		copy(dAtA[i:], m.BabylonHeaderHash)
		i = encodeVarintZoneconcierge(dAtA, i, uint64(len(m.BabylonHeaderHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Time != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Time, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Time):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintZoneconcierge(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x22
	}
	if m.Height != 0 {
		i = encodeVarintZoneconcierge(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintZoneconcierge(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintZoneconcierge(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Forks) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Forks) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Forks) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Headers) > 0 {
		for iNdEx := len(m.Headers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Headers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	return len(dAtA) - i, nil
}

func (m *ChainInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimestampedHeadersCount != 0 {
		i = encodeVarintZoneconcierge(dAtA, i, uint64(m.TimestampedHeadersCount))
		i--
		dAtA[i] = 0x20
	}
	if m.LatestForks != nil {
		{
			size, err := m.LatestForks.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.LatestHeader != nil {
		{
			size, err := m.LatestHeader.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintZoneconcierge(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ChainRegister) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainRegister) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainRegister) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainDescription) > 0 {
		i -= len(m.ChainDescription)
		copy(dAtA[i:], m.ChainDescription)
		i = encodeVarintZoneconcierge(dAtA, i, uint64(len(m.ChainDescription)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChainName) > 0 {
		i -= len(m.ChainName)
		copy(dAtA[i:], m.ChainName)
		i = encodeVarintZoneconcierge(dAtA, i, uint64(len(m.ChainName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintZoneconcierge(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FinalizedChainInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FinalizedChainInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FinalizedChainInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Proof != nil {
		{
			size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.BtcSubmissionKey != nil {
		{
			size, err := m.BtcSubmissionKey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.RawCheckpoint != nil {
		{
			size, err := m.RawCheckpoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.EpochInfo != nil {
		{
			size, err := m.EpochInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.FinalizedChainInfo != nil {
		{
			size, err := m.FinalizedChainInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintZoneconcierge(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProofEpochSealed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProofEpochSealed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProofEpochSealed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProofEpochValSet != nil {
		{
			size, err := m.ProofEpochValSet.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ProofEpochInfo != nil {
		{
			size, err := m.ProofEpochInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorSet) > 0 {
		for iNdEx := len(m.ValidatorSet) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorSet[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ProofFinalizedChainInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProofFinalizedChainInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProofFinalizedChainInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProofEpochSubmitted) > 0 {
		for iNdEx := len(m.ProofEpochSubmitted) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ProofEpochSubmitted[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ProofEpochSealed != nil {
		{
			size, err := m.ProofEpochSealed.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.ProofCzHeaderInEpoch != nil {
		{
			size, err := m.ProofCzHeaderInEpoch.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BTCChainSegment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BTCChainSegment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BTCChainSegment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BtcHeaders) > 0 {
		for iNdEx := len(m.BtcHeaders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BtcHeaders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintZoneconcierge(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintZoneconcierge(dAtA []byte, offset int, v uint64) int {
	offset -= sovZoneconcierge(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IndexedHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovZoneconcierge(uint64(m.Height))
	}
	if m.Time != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Time)
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	l = len(m.BabylonHeaderHash)
	if l > 0 {
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if m.BabylonHeaderHeight != 0 {
		n += 1 + sovZoneconcierge(uint64(m.BabylonHeaderHeight))
	}
	if m.BabylonEpoch != 0 {
		n += 1 + sovZoneconcierge(uint64(m.BabylonEpoch))
	}
	l = len(m.BabylonTxHash)
	if l > 0 {
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	return n
}

func (m *Forks) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Headers) > 0 {
		for _, e := range m.Headers {
			l = e.Size()
			n += 1 + l + sovZoneconcierge(uint64(l))
		}
	}
	return n
}

func (m *ChainInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if m.LatestHeader != nil {
		l = m.LatestHeader.Size()
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if m.LatestForks != nil {
		l = m.LatestForks.Size()
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if m.TimestampedHeadersCount != 0 {
		n += 1 + sovZoneconcierge(uint64(m.TimestampedHeadersCount))
	}
	return n
}

func (m *ChainRegister) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	l = len(m.ChainName)
	if l > 0 {
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	l = len(m.ChainDescription)
	if l > 0 {
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	return n
}

func (m *FinalizedChainInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if m.FinalizedChainInfo != nil {
		l = m.FinalizedChainInfo.Size()
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if m.EpochInfo != nil {
		l = m.EpochInfo.Size()
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if m.RawCheckpoint != nil {
		l = m.RawCheckpoint.Size()
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if m.BtcSubmissionKey != nil {
		l = m.BtcSubmissionKey.Size()
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if m.Proof != nil {
		l = m.Proof.Size()
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	return n
}

func (m *ProofEpochSealed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ValidatorSet) > 0 {
		for _, e := range m.ValidatorSet {
			l = e.Size()
			n += 1 + l + sovZoneconcierge(uint64(l))
		}
	}
	if m.ProofEpochInfo != nil {
		l = m.ProofEpochInfo.Size()
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if m.ProofEpochValSet != nil {
		l = m.ProofEpochValSet.Size()
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	return n
}

func (m *ProofFinalizedChainInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProofCzHeaderInEpoch != nil {
		l = m.ProofCzHeaderInEpoch.Size()
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if m.ProofEpochSealed != nil {
		l = m.ProofEpochSealed.Size()
		n += 1 + l + sovZoneconcierge(uint64(l))
	}
	if len(m.ProofEpochSubmitted) > 0 {
		for _, e := range m.ProofEpochSubmitted {
			l = e.Size()
			n += 1 + l + sovZoneconcierge(uint64(l))
		}
	}
	return n
}

func (m *BTCChainSegment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.BtcHeaders) > 0 {
		for _, e := range m.BtcHeaders {
			l = e.Size()
			n += 1 + l + sovZoneconcierge(uint64(l))
		}
	}
	return n
}

func sovZoneconcierge(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozZoneconcierge(x uint64) (n int) {
	return sovZoneconcierge(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IndexedHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZoneconcierge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndexedHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndexedHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Time == nil {
				m.Time = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BabylonHeaderHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BabylonHeaderHash = append(m.BabylonHeaderHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BabylonHeaderHash == nil {
				m.BabylonHeaderHash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BabylonHeaderHeight", wireType)
			}
			m.BabylonHeaderHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BabylonHeaderHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BabylonEpoch", wireType)
			}
			m.BabylonEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BabylonEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BabylonTxHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BabylonTxHash = append(m.BabylonTxHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BabylonTxHash == nil {
				m.BabylonTxHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZoneconcierge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Forks) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZoneconcierge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Forks: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Forks: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Headers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Headers = append(m.Headers, &IndexedHeader{})
			if err := m.Headers[len(m.Headers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZoneconcierge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChainInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZoneconcierge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LatestHeader == nil {
				m.LatestHeader = &IndexedHeader{}
			}
			if err := m.LatestHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestForks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LatestForks == nil {
				m.LatestForks = &Forks{}
			}
			if err := m.LatestForks.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampedHeadersCount", wireType)
			}
			m.TimestampedHeadersCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimestampedHeadersCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipZoneconcierge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChainRegister) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZoneconcierge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainRegister: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainRegister: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZoneconcierge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FinalizedChainInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZoneconcierge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FinalizedChainInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FinalizedChainInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedChainInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FinalizedChainInfo == nil {
				m.FinalizedChainInfo = &ChainInfo{}
			}
			if err := m.FinalizedChainInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EpochInfo == nil {
				m.EpochInfo = &types.Epoch{}
			}
			if err := m.EpochInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawCheckpoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RawCheckpoint == nil {
				m.RawCheckpoint = &types1.RawCheckpoint{}
			}
			if err := m.RawCheckpoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcSubmissionKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BtcSubmissionKey == nil {
				m.BtcSubmissionKey = &types2.SubmissionKey{}
			}
			if err := m.BtcSubmissionKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proof == nil {
				m.Proof = &ProofFinalizedChainInfo{}
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZoneconcierge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProofEpochSealed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZoneconcierge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProofEpochSealed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProofEpochSealed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorSet = append(m.ValidatorSet, &types1.ValidatorWithBlsKey{})
			if err := m.ValidatorSet[len(m.ValidatorSet)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofEpochInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProofEpochInfo == nil {
				m.ProofEpochInfo = &crypto.ProofOps{}
			}
			if err := m.ProofEpochInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofEpochValSet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProofEpochValSet == nil {
				m.ProofEpochValSet = &crypto.ProofOps{}
			}
			if err := m.ProofEpochValSet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZoneconcierge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProofFinalizedChainInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZoneconcierge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProofFinalizedChainInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProofFinalizedChainInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofCzHeaderInEpoch", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProofCzHeaderInEpoch == nil {
				m.ProofCzHeaderInEpoch = &crypto.ProofOps{}
			}
			if err := m.ProofCzHeaderInEpoch.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofEpochSealed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProofEpochSealed == nil {
				m.ProofEpochSealed = &ProofEpochSealed{}
			}
			if err := m.ProofEpochSealed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofEpochSubmitted", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProofEpochSubmitted = append(m.ProofEpochSubmitted, &types2.TransactionInfo{})
			if err := m.ProofEpochSubmitted[len(m.ProofEpochSubmitted)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZoneconcierge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BTCChainSegment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZoneconcierge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BTCChainSegment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BTCChainSegment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcHeaders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcHeaders = append(m.BtcHeaders, &types3.BTCHeaderInfo{})
			if err := m.BtcHeaders[len(m.BtcHeaders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZoneconcierge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZoneconcierge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipZoneconcierge(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowZoneconcierge
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowZoneconcierge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthZoneconcierge
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupZoneconcierge
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthZoneconcierge
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthZoneconcierge        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowZoneconcierge          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupZoneconcierge = fmt.Errorf("proto: unexpected end of group")
)
