// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babylon/btcstaking/v1/incentive.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	github_com_babylonlabs_io_babylon_types "github.com/babylonlabs-io/babylon/types"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// VotingPowerDistCache is the cache for voting power distribution of finality providers
// and their BTC delegations at a height
type VotingPowerDistCache struct {
	// total_sat is the total amount of bonded BTC stake (in Satoshi) of all the finality providers
	// in the cache
	TotalBondedSat uint64 `protobuf:"varint,1,opt,name=total_bonded_sat,json=totalBondedSat,proto3" json:"total_bonded_sat,omitempty"`
	// finality_providers is a list of finality providers' voting power information
	FinalityProviders []*FinalityProviderDistInfo `protobuf:"bytes,2,rep,name=finality_providers,json=finalityProviders,proto3" json:"finality_providers,omitempty"`
	// num_active_fps is the number of finality providers that have active BTC
	// delegations as well as timestamped public randomness
	NumActiveFps uint32 `protobuf:"varint,3,opt,name=num_active_fps,json=numActiveFps,proto3" json:"num_active_fps,omitempty"`
}

func (m *VotingPowerDistCache) Reset()         { *m = VotingPowerDistCache{} }
func (m *VotingPowerDistCache) String() string { return proto.CompactTextString(m) }
func (*VotingPowerDistCache) ProtoMessage()    {}
func (*VotingPowerDistCache) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac354c3bd6d7a66b, []int{0}
}
func (m *VotingPowerDistCache) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VotingPowerDistCache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VotingPowerDistCache.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VotingPowerDistCache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VotingPowerDistCache.Merge(m, src)
}
func (m *VotingPowerDistCache) XXX_Size() int {
	return m.Size()
}
func (m *VotingPowerDistCache) XXX_DiscardUnknown() {
	xxx_messageInfo_VotingPowerDistCache.DiscardUnknown(m)
}

var xxx_messageInfo_VotingPowerDistCache proto.InternalMessageInfo

// FinalityProviderDistInfo is the reward distribution of a finality provider and its BTC delegations
type FinalityProviderDistInfo struct {
	// btc_pk is the Bitcoin secp256k1 PK of this finality provider
	// the PK follows encoding in BIP-340 spec
	BtcPk *github_com_babylonlabs_io_babylon_types.BIP340PubKey `protobuf:"bytes,1,opt,name=btc_pk,json=btcPk,proto3,customtype=github.com/babylonlabs-io/babylon/types.BIP340PubKey" json:"btc_pk,omitempty"`
	// addr is the address to receive commission from delegations.
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// commission defines the commission rate of finality provider
	Commission *cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=commission,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"commission,omitempty"`
	// total_bonded_sat is the total amount of bonded BTC stake (in Satoshi) of the finality provider
	TotalBondedSat uint64 `protobuf:"varint,4,opt,name=total_bonded_sat,json=totalBondedSat,proto3" json:"total_bonded_sat,omitempty"`
	// btc_dels is a list of BTC delegations' voting power information under this finality provider
	BtcDels []*BTCDelDistInfo `protobuf:"bytes,5,rep,name=btc_dels,json=btcDels,proto3" json:"btc_dels,omitempty"`
	// is_timestamped indicates whether the finality provider
	// has timestamped public randomness committed
	// if no, it should not be assigned voting power
	IsTimestamped bool `protobuf:"varint,6,opt,name=is_timestamped,json=isTimestamped,proto3" json:"is_timestamped,omitempty"`
	// is_jailed indicates whether the finality provider
	// is jailed, if so, it should not be assigned voting power
	IsJailed bool `protobuf:"varint,7,opt,name=is_jailed,json=isJailed,proto3" json:"is_jailed,omitempty"`
	// is_slashed indicates whether the finality provider
	// is slashed, if so, it should not be assigned voting power
	IsSlashed bool `protobuf:"varint,8,opt,name=is_slashed,json=isSlashed,proto3" json:"is_slashed,omitempty"`
}

func (m *FinalityProviderDistInfo) Reset()         { *m = FinalityProviderDistInfo{} }
func (m *FinalityProviderDistInfo) String() string { return proto.CompactTextString(m) }
func (*FinalityProviderDistInfo) ProtoMessage()    {}
func (*FinalityProviderDistInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac354c3bd6d7a66b, []int{1}
}
func (m *FinalityProviderDistInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FinalityProviderDistInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FinalityProviderDistInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FinalityProviderDistInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalityProviderDistInfo.Merge(m, src)
}
func (m *FinalityProviderDistInfo) XXX_Size() int {
	return m.Size()
}
func (m *FinalityProviderDistInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalityProviderDistInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FinalityProviderDistInfo proto.InternalMessageInfo

func (m *FinalityProviderDistInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *FinalityProviderDistInfo) GetTotalBondedSat() uint64 {
	if m != nil {
		return m.TotalBondedSat
	}
	return 0
}

func (m *FinalityProviderDistInfo) GetBtcDels() []*BTCDelDistInfo {
	if m != nil {
		return m.BtcDels
	}
	return nil
}

func (m *FinalityProviderDistInfo) GetIsTimestamped() bool {
	if m != nil {
		return m.IsTimestamped
	}
	return false
}

func (m *FinalityProviderDistInfo) GetIsJailed() bool {
	if m != nil {
		return m.IsJailed
	}
	return false
}

func (m *FinalityProviderDistInfo) GetIsSlashed() bool {
	if m != nil {
		return m.IsSlashed
	}
	return false
}

// BTCDelDistInfo contains the information related to voting power distribution for a BTC delegation
type BTCDelDistInfo struct {
	// btc_pk is the Bitcoin secp256k1 PK of this BTC delegation
	// the PK follows encoding in BIP-340 spec
	BtcPk *github_com_babylonlabs_io_babylon_types.BIP340PubKey `protobuf:"bytes,1,opt,name=btc_pk,json=btcPk,proto3,customtype=github.com/babylonlabs-io/babylon/types.BIP340PubKey" json:"btc_pk,omitempty"`
	// staker_addr is the address to receive rewards from BTC delegation.
	StakerAddr string `protobuf:"bytes,2,opt,name=staker_addr,json=stakerAddr,proto3" json:"staker_addr,omitempty"`
	// staking_tx_hash is the staking tx hash of the BTC delegation
	StakingTxHash string `protobuf:"bytes,3,opt,name=staking_tx_hash,json=stakingTxHash,proto3" json:"staking_tx_hash,omitempty"`
	// total_sat is the amount of BTC stake (in Satoshi) of the BTC delegation
	TotalSat uint64 `protobuf:"varint,4,opt,name=total_sat,json=totalSat,proto3" json:"total_sat,omitempty"`
}

func (m *BTCDelDistInfo) Reset()         { *m = BTCDelDistInfo{} }
func (m *BTCDelDistInfo) String() string { return proto.CompactTextString(m) }
func (*BTCDelDistInfo) ProtoMessage()    {}
func (*BTCDelDistInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac354c3bd6d7a66b, []int{2}
}
func (m *BTCDelDistInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BTCDelDistInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BTCDelDistInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BTCDelDistInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BTCDelDistInfo.Merge(m, src)
}
func (m *BTCDelDistInfo) XXX_Size() int {
	return m.Size()
}
func (m *BTCDelDistInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BTCDelDistInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BTCDelDistInfo proto.InternalMessageInfo

func (m *BTCDelDistInfo) GetStakerAddr() string {
	if m != nil {
		return m.StakerAddr
	}
	return ""
}

func (m *BTCDelDistInfo) GetStakingTxHash() string {
	if m != nil {
		return m.StakingTxHash
	}
	return ""
}

func (m *BTCDelDistInfo) GetTotalSat() uint64 {
	if m != nil {
		return m.TotalSat
	}
	return 0
}

func init() {
	proto.RegisterType((*VotingPowerDistCache)(nil), "babylon.btcstaking.v1.VotingPowerDistCache")
	proto.RegisterType((*FinalityProviderDistInfo)(nil), "babylon.btcstaking.v1.FinalityProviderDistInfo")
	proto.RegisterType((*BTCDelDistInfo)(nil), "babylon.btcstaking.v1.BTCDelDistInfo")
}

func init() {
	proto.RegisterFile("babylon/btcstaking/v1/incentive.proto", fileDescriptor_ac354c3bd6d7a66b)
}

var fileDescriptor_ac354c3bd6d7a66b = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x4f, 0x4f, 0x13, 0x41,
	0x18, 0xc6, 0xbb, 0x50, 0xa0, 0x1d, 0xa0, 0xea, 0x06, 0x93, 0x15, 0x62, 0x69, 0x88, 0x98, 0x1e,
	0xec, 0xae, 0x08, 0x07, 0xf5, 0x24, 0x4b, 0x43, 0xc4, 0xbf, 0xcd, 0x96, 0x78, 0xf0, 0xe0, 0x66,
	0x76, 0x66, 0xba, 0x3b, 0x76, 0x77, 0xa6, 0xd9, 0x77, 0x5a, 0xe9, 0x37, 0xf0, 0xe8, 0x47, 0xf0,
	0x43, 0x90, 0xf8, 0x15, 0x3c, 0x78, 0x20, 0x9c, 0x0c, 0x07, 0xa2, 0xf0, 0x45, 0xcc, 0xce, 0xae,
	0x82, 0x06, 0x12, 0x0e, 0xde, 0x3a, 0xcf, 0xfb, 0xcc, 0xfb, 0xce, 0xf3, 0xfe, 0xd2, 0x45, 0xab,
	0x01, 0x0e, 0xc6, 0xb1, 0x14, 0x4e, 0xa0, 0x08, 0x28, 0xdc, 0xe7, 0x22, 0x74, 0x46, 0x6b, 0x0e,
	0x17, 0x84, 0x09, 0xc5, 0x47, 0xcc, 0x1e, 0xa4, 0x52, 0x49, 0xf3, 0x66, 0x61, 0xb3, 0xcf, 0x6c,
	0xf6, 0x68, 0x6d, 0x71, 0x21, 0x94, 0xa1, 0xd4, 0x0e, 0x27, 0xfb, 0x95, 0x9b, 0x17, 0x6f, 0x11,
	0x09, 0x89, 0x04, 0x3f, 0x2f, 0xe4, 0x87, 0xbc, 0xb4, 0xf2, 0xcd, 0x40, 0x0b, 0x6f, 0xa4, 0xe2,
	0x22, 0xec, 0xc8, 0x0f, 0x2c, 0x6d, 0x73, 0x50, 0x5b, 0x98, 0x44, 0xcc, 0x6c, 0xa2, 0xeb, 0x4a,
	0x2a, 0x1c, 0xfb, 0x81, 0x14, 0x94, 0x51, 0x1f, 0xb0, 0xb2, 0x8c, 0x86, 0xd1, 0x2c, 0x7b, 0x35,
	0xad, 0xbb, 0x5a, 0xee, 0x62, 0x65, 0xbe, 0x43, 0x66, 0x8f, 0x0b, 0x1c, 0x73, 0x35, 0xce, 0x26,
	0x8c, 0x38, 0x65, 0x29, 0x58, 0x13, 0x8d, 0xc9, 0xe6, 0xec, 0x03, 0xc7, 0xbe, 0xf0, 0x9d, 0xf6,
	0x76, 0x71, 0xa1, 0x53, 0xf8, 0xb3, 0xb9, 0x3b, 0xa2, 0x27, 0xbd, 0x1b, 0xbd, 0x7f, 0x2a, 0x60,
	0xde, 0x41, 0x35, 0x31, 0x4c, 0x7c, 0x4c, 0xb2, 0xf8, 0x7e, 0x6f, 0x00, 0xd6, 0x64, 0xc3, 0x68,
	0xce, 0x7b, 0x73, 0x62, 0x98, 0x6c, 0x6a, 0x71, 0x7b, 0x00, 0x8f, 0xcb, 0x1f, 0x3f, 0x2f, 0x97,
	0x56, 0xbe, 0x4c, 0x22, 0xeb, 0xb2, 0xde, 0xe6, 0x6b, 0x34, 0x1d, 0x28, 0xe2, 0x0f, 0xfa, 0x3a,
	0xc8, 0x9c, 0xfb, 0xf0, 0xe8, 0x78, 0x79, 0x23, 0xe4, 0x2a, 0x1a, 0x06, 0x36, 0x91, 0x89, 0x53,
	0x3c, 0x35, 0xc6, 0x01, 0xb4, 0xb8, 0xfc, 0x7d, 0x74, 0xd4, 0x78, 0xc0, 0xc0, 0x76, 0x77, 0x3a,
	0xeb, 0x1b, 0xf7, 0x3b, 0xc3, 0xe0, 0x39, 0x1b, 0x7b, 0x53, 0x81, 0x22, 0x9d, 0xbe, 0x79, 0x0f,
	0x95, 0x31, 0xa5, 0xa9, 0x35, 0xd1, 0x30, 0x9a, 0x55, 0xd7, 0x3a, 0xdc, 0x6f, 0x2d, 0x14, 0xcb,
	0xdd, 0xa4, 0x34, 0x65, 0x00, 0x5d, 0x95, 0x72, 0x11, 0x7a, 0xda, 0x65, 0xbe, 0x44, 0x88, 0xc8,
	0x24, 0xe1, 0x00, 0x5c, 0x0a, 0x9d, 0xa1, 0xea, 0xb6, 0x8e, 0x8e, 0x97, 0x97, 0xf2, 0x3b, 0x40,
	0xfb, 0x36, 0x97, 0x4e, 0x82, 0x55, 0x64, 0xbf, 0x60, 0x21, 0x26, 0xe3, 0x36, 0x23, 0x87, 0xfb,
	0x2d, 0x54, 0xb4, 0x6c, 0x33, 0xe2, 0x9d, 0x6b, 0x70, 0x21, 0xa0, 0xf2, 0x85, 0x80, 0x9e, 0xa0,
	0x4a, 0x96, 0x9b, 0xb2, 0x18, 0xac, 0x29, 0x8d, 0x65, 0xf5, 0x12, 0x2c, 0xee, 0xee, 0x56, 0x9b,
	0xc5, 0x7f, 0x60, 0xcc, 0x04, 0x8a, 0xb4, 0x59, 0x0c, 0xe6, 0x2a, 0xaa, 0x71, 0xf0, 0x15, 0x4f,
	0x18, 0x28, 0x9c, 0x0c, 0x18, 0xb5, 0xa6, 0x1b, 0x46, 0xb3, 0xe2, 0xcd, 0x73, 0xd8, 0x3d, 0x13,
	0xcd, 0x25, 0x54, 0xe5, 0xe0, 0xbf, 0xc7, 0x3c, 0x66, 0xd4, 0x9a, 0xd1, 0x8e, 0x0a, 0x87, 0x67,
	0xfa, 0x6c, 0xde, 0x46, 0x88, 0x83, 0x0f, 0x31, 0x86, 0x88, 0x51, 0xab, 0xa2, 0xab, 0x55, 0x0e,
	0xdd, 0x5c, 0x58, 0xf9, 0x69, 0xa0, 0xda, 0xdf, 0xe3, 0xff, 0x3f, 0xaf, 0x47, 0x68, 0x36, 0x0b,
	0xcb, 0x52, 0xff, 0x4a, 0xd8, 0x50, 0x6e, 0xce, 0x44, 0xf3, 0x2e, 0xba, 0x56, 0xec, 0xc9, 0x57,
	0x7b, 0x7e, 0x84, 0x21, 0xca, 0x09, 0x7a, 0xf3, 0x85, 0xbc, 0xbb, 0xf7, 0x14, 0x43, 0x94, 0xad,
	0x20, 0xa7, 0x72, 0x86, 0xa3, 0xa2, 0x85, 0x2e, 0x56, 0xee, 0xab, 0xaf, 0x27, 0x75, 0xe3, 0xe0,
	0xa4, 0x6e, 0xfc, 0x38, 0xa9, 0x1b, 0x9f, 0x4e, 0xeb, 0xa5, 0x83, 0xd3, 0x7a, 0xe9, 0xfb, 0x69,
	0xbd, 0xf4, 0xf6, 0x0a, 0xb1, 0xf6, 0xce, 0x7f, 0x11, 0x74, 0xc6, 0x60, 0x5a, 0xff, 0x87, 0xd7,
	0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xc9, 0x06, 0x18, 0x34, 0x04, 0x00, 0x00,
}

func (m *VotingPowerDistCache) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VotingPowerDistCache) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VotingPowerDistCache) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NumActiveFps != 0 {
		i = encodeVarintIncentive(dAtA, i, uint64(m.NumActiveFps))
		i--
		dAtA[i] = 0x18
	}
	if len(m.FinalityProviders) > 0 {
		for iNdEx := len(m.FinalityProviders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FinalityProviders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintIncentive(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.TotalBondedSat != 0 {
		i = encodeVarintIncentive(dAtA, i, uint64(m.TotalBondedSat))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FinalityProviderDistInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FinalityProviderDistInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FinalityProviderDistInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsSlashed {
		i--
		if m.IsSlashed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.IsJailed {
		i--
		if m.IsJailed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.IsTimestamped {
		i--
		if m.IsTimestamped {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.BtcDels) > 0 {
		for iNdEx := len(m.BtcDels) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BtcDels[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintIncentive(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.TotalBondedSat != 0 {
		i = encodeVarintIncentive(dAtA, i, uint64(m.TotalBondedSat))
		i--
		dAtA[i] = 0x20
	}
	if m.Commission != nil {
		{
			size := m.Commission.Size()
			i -= size
			if _, err := m.Commission.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintIncentive(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintIncentive(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0x12
	}
	if m.BtcPk != nil {
		{
			size := m.BtcPk.Size()
			i -= size
			if _, err := m.BtcPk.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintIncentive(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BTCDelDistInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BTCDelDistInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BTCDelDistInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalSat != 0 {
		i = encodeVarintIncentive(dAtA, i, uint64(m.TotalSat))
		i--
		dAtA[i] = 0x20
	}
	if len(m.StakingTxHash) > 0 {
		i -= len(m.StakingTxHash)
		copy(dAtA[i:], m.StakingTxHash)
		i = encodeVarintIncentive(dAtA, i, uint64(len(m.StakingTxHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.StakerAddr) > 0 {
		i -= len(m.StakerAddr)
		copy(dAtA[i:], m.StakerAddr)
		i = encodeVarintIncentive(dAtA, i, uint64(len(m.StakerAddr)))
		i--
		dAtA[i] = 0x12
	}
	if m.BtcPk != nil {
		{
			size := m.BtcPk.Size()
			i -= size
			if _, err := m.BtcPk.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintIncentive(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIncentive(dAtA []byte, offset int, v uint64) int {
	offset -= sovIncentive(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VotingPowerDistCache) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalBondedSat != 0 {
		n += 1 + sovIncentive(uint64(m.TotalBondedSat))
	}
	if len(m.FinalityProviders) > 0 {
		for _, e := range m.FinalityProviders {
			l = e.Size()
			n += 1 + l + sovIncentive(uint64(l))
		}
	}
	if m.NumActiveFps != 0 {
		n += 1 + sovIncentive(uint64(m.NumActiveFps))
	}
	return n
}

func (m *FinalityProviderDistInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BtcPk != nil {
		l = m.BtcPk.Size()
		n += 1 + l + sovIncentive(uint64(l))
	}
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovIncentive(uint64(l))
	}
	if m.Commission != nil {
		l = m.Commission.Size()
		n += 1 + l + sovIncentive(uint64(l))
	}
	if m.TotalBondedSat != 0 {
		n += 1 + sovIncentive(uint64(m.TotalBondedSat))
	}
	if len(m.BtcDels) > 0 {
		for _, e := range m.BtcDels {
			l = e.Size()
			n += 1 + l + sovIncentive(uint64(l))
		}
	}
	if m.IsTimestamped {
		n += 2
	}
	if m.IsJailed {
		n += 2
	}
	if m.IsSlashed {
		n += 2
	}
	return n
}

func (m *BTCDelDistInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BtcPk != nil {
		l = m.BtcPk.Size()
		n += 1 + l + sovIncentive(uint64(l))
	}
	l = len(m.StakerAddr)
	if l > 0 {
		n += 1 + l + sovIncentive(uint64(l))
	}
	l = len(m.StakingTxHash)
	if l > 0 {
		n += 1 + l + sovIncentive(uint64(l))
	}
	if m.TotalSat != 0 {
		n += 1 + sovIncentive(uint64(m.TotalSat))
	}
	return n
}

func sovIncentive(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIncentive(x uint64) (n int) {
	return sovIncentive(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VotingPowerDistCache) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIncentive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VotingPowerDistCache: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VotingPowerDistCache: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBondedSat", wireType)
			}
			m.TotalBondedSat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalBondedSat |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalityProviders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIncentive
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIncentive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalityProviders = append(m.FinalityProviders, &FinalityProviderDistInfo{})
			if err := m.FinalityProviders[len(m.FinalityProviders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumActiveFps", wireType)
			}
			m.NumActiveFps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumActiveFps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIncentive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIncentive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FinalityProviderDistInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIncentive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FinalityProviderDistInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FinalityProviderDistInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcPk", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIncentive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIncentive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_babylonlabs_io_babylon_types.BIP340PubKey
			m.BtcPk = &v
			if err := m.BtcPk.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncentive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncentive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commission", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncentive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncentive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.Commission = &v
			if err := m.Commission.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBondedSat", wireType)
			}
			m.TotalBondedSat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalBondedSat |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcDels", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIncentive
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIncentive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcDels = append(m.BtcDels, &BTCDelDistInfo{})
			if err := m.BtcDels[len(m.BtcDels)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsTimestamped", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsTimestamped = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsJailed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsJailed = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSlashed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsSlashed = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipIncentive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIncentive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BTCDelDistInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIncentive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BTCDelDistInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BTCDelDistInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcPk", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIncentive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIncentive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_babylonlabs_io_babylon_types.BIP340PubKey
			m.BtcPk = &v
			if err := m.BtcPk.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakerAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncentive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncentive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakerAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncentive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncentive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSat", wireType)
			}
			m.TotalSat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalSat |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIncentive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIncentive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIncentive(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIncentive
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIncentive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIncentive
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIncentive
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIncentive
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIncentive        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIncentive          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIncentive = fmt.Errorf("proto: unexpected end of group")
)
