// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babylon/btcstkconsumer/v1/btcstkconsumer.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ConsumerType defines the type of consumer chain
type ConsumerType int32

const (
	// COSMOS represents a Cosmos SDK chain consumer
	ConsumerType_COSMOS ConsumerType = 0
	// ROLLUP represents a rollup chain consumer
	ConsumerType_ROLLUP ConsumerType = 1
)

var ConsumerType_name = map[int32]string{
	0: "COSMOS",
	1: "ROLLUP",
}

var ConsumerType_value = map[string]int32{
	"COSMOS": 0,
	"ROLLUP": 1,
}

func (x ConsumerType) String() string {
	return proto.EnumName(ConsumerType_name, int32(x))
}

func (ConsumerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de3ccd621fe1efd4, []int{0}
}

// ConsumerRegister is the registration information of a consumer
type ConsumerRegister struct {
	// consumer_id is the ID of the consumer
	// - for Cosmos SDK chains, the consumer ID will be the IBC client ID
	// - for rollup chains, the consumer ID will be the chain ID of the rollup
	//   chain
	ConsumerId string `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// consumer_name is the name of the consumer
	ConsumerName string `protobuf:"bytes,2,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	// consumer_description is a description for the consumer (can be empty)
	ConsumerDescription string `protobuf:"bytes,3,opt,name=consumer_description,json=consumerDescription,proto3" json:"consumer_description,omitempty"`
	// max_multi_staked_fps is the maximum number of finality providers from this consumer
	// that can be part of a single BTC delegation. Must be at least 2 to allow for at least
	// one Babylon FP and one consumer FP.
	MaxMultiStakedFps uint32 `protobuf:"varint,4,opt,name=max_multi_staked_fps,json=maxMultiStakedFps,proto3" json:"max_multi_staked_fps,omitempty"`
	// consumer_metadata is necessary metadata of the consumer, and the data
	// depends on the type of integration
	//
	// Types that are valid to be assigned to ConsumerMetadata:
	//	*ConsumerRegister_CosmosConsumerMetadata
	//	*ConsumerRegister_RollupConsumerMetadata
	ConsumerMetadata isConsumerRegister_ConsumerMetadata `protobuf_oneof:"consumer_metadata"`
}

func (m *ConsumerRegister) Reset()         { *m = ConsumerRegister{} }
func (m *ConsumerRegister) String() string { return proto.CompactTextString(m) }
func (*ConsumerRegister) ProtoMessage()    {}
func (*ConsumerRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_de3ccd621fe1efd4, []int{0}
}
func (m *ConsumerRegister) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsumerRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsumerRegister.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsumerRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerRegister.Merge(m, src)
}
func (m *ConsumerRegister) XXX_Size() int {
	return m.Size()
}
func (m *ConsumerRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerRegister proto.InternalMessageInfo

type isConsumerRegister_ConsumerMetadata interface {
	isConsumerRegister_ConsumerMetadata()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ConsumerRegister_CosmosConsumerMetadata struct {
	CosmosConsumerMetadata *CosmosConsumerMetadata `protobuf:"bytes,5,opt,name=cosmos_consumer_metadata,json=cosmosConsumerMetadata,proto3,oneof" json:"cosmos_consumer_metadata,omitempty"`
}
type ConsumerRegister_RollupConsumerMetadata struct {
	RollupConsumerMetadata *RollupConsumerMetadata `protobuf:"bytes,6,opt,name=rollup_consumer_metadata,json=rollupConsumerMetadata,proto3,oneof" json:"rollup_consumer_metadata,omitempty"`
}

func (*ConsumerRegister_CosmosConsumerMetadata) isConsumerRegister_ConsumerMetadata() {}
func (*ConsumerRegister_RollupConsumerMetadata) isConsumerRegister_ConsumerMetadata() {}

func (m *ConsumerRegister) GetConsumerMetadata() isConsumerRegister_ConsumerMetadata {
	if m != nil {
		return m.ConsumerMetadata
	}
	return nil
}

func (m *ConsumerRegister) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

func (m *ConsumerRegister) GetConsumerName() string {
	if m != nil {
		return m.ConsumerName
	}
	return ""
}

func (m *ConsumerRegister) GetConsumerDescription() string {
	if m != nil {
		return m.ConsumerDescription
	}
	return ""
}

func (m *ConsumerRegister) GetMaxMultiStakedFps() uint32 {
	if m != nil {
		return m.MaxMultiStakedFps
	}
	return 0
}

func (m *ConsumerRegister) GetCosmosConsumerMetadata() *CosmosConsumerMetadata {
	if x, ok := m.GetConsumerMetadata().(*ConsumerRegister_CosmosConsumerMetadata); ok {
		return x.CosmosConsumerMetadata
	}
	return nil
}

func (m *ConsumerRegister) GetRollupConsumerMetadata() *RollupConsumerMetadata {
	if x, ok := m.GetConsumerMetadata().(*ConsumerRegister_RollupConsumerMetadata); ok {
		return x.RollupConsumerMetadata
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ConsumerRegister) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ConsumerRegister_CosmosConsumerMetadata)(nil),
		(*ConsumerRegister_RollupConsumerMetadata)(nil),
	}
}

// CosmosConsumerMetadata is the metadata for the Cosmos integration
type CosmosConsumerMetadata struct {
	// channel_id defines the IBC channel ID for the consumer chain
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (m *CosmosConsumerMetadata) Reset()         { *m = CosmosConsumerMetadata{} }
func (m *CosmosConsumerMetadata) String() string { return proto.CompactTextString(m) }
func (*CosmosConsumerMetadata) ProtoMessage()    {}
func (*CosmosConsumerMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_de3ccd621fe1efd4, []int{1}
}
func (m *CosmosConsumerMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CosmosConsumerMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CosmosConsumerMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CosmosConsumerMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CosmosConsumerMetadata.Merge(m, src)
}
func (m *CosmosConsumerMetadata) XXX_Size() int {
	return m.Size()
}
func (m *CosmosConsumerMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_CosmosConsumerMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_CosmosConsumerMetadata proto.InternalMessageInfo

func (m *CosmosConsumerMetadata) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

// RollupConsumerMetadata is the metadata for the rollup integration
type RollupConsumerMetadata struct {
	// finality_contract_address is the address of the finality contract for
	// the rollup integration
	FinalityContractAddress string `protobuf:"bytes,1,opt,name=finality_contract_address,json=finalityContractAddress,proto3" json:"finality_contract_address,omitempty"`
}

func (m *RollupConsumerMetadata) Reset()         { *m = RollupConsumerMetadata{} }
func (m *RollupConsumerMetadata) String() string { return proto.CompactTextString(m) }
func (*RollupConsumerMetadata) ProtoMessage()    {}
func (*RollupConsumerMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_de3ccd621fe1efd4, []int{2}
}
func (m *RollupConsumerMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RollupConsumerMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RollupConsumerMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RollupConsumerMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollupConsumerMetadata.Merge(m, src)
}
func (m *RollupConsumerMetadata) XXX_Size() int {
	return m.Size()
}
func (m *RollupConsumerMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RollupConsumerMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RollupConsumerMetadata proto.InternalMessageInfo

func (m *RollupConsumerMetadata) GetFinalityContractAddress() string {
	if m != nil {
		return m.FinalityContractAddress
	}
	return ""
}

func init() {
	proto.RegisterEnum("babylon.btcstkconsumer.v1.ConsumerType", ConsumerType_name, ConsumerType_value)
	proto.RegisterType((*ConsumerRegister)(nil), "babylon.btcstkconsumer.v1.ConsumerRegister")
	proto.RegisterType((*CosmosConsumerMetadata)(nil), "babylon.btcstkconsumer.v1.CosmosConsumerMetadata")
	proto.RegisterType((*RollupConsumerMetadata)(nil), "babylon.btcstkconsumer.v1.RollupConsumerMetadata")
}

func init() {
	proto.RegisterFile("babylon/btcstkconsumer/v1/btcstkconsumer.proto", fileDescriptor_de3ccd621fe1efd4)
}

var fileDescriptor_de3ccd621fe1efd4 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xc1, 0x6e, 0xd3, 0x30,
	0x1c, 0xc6, 0x13, 0x06, 0x95, 0xf6, 0xdf, 0x26, 0x75, 0x5e, 0x55, 0x52, 0x24, 0x42, 0x55, 0x24,
	0x54, 0x21, 0x2d, 0x51, 0x01, 0x89, 0x03, 0x27, 0x5a, 0x84, 0x98, 0xb4, 0x52, 0x94, 0x6e, 0x17,
	0x2e, 0x91, 0x93, 0x78, 0x9d, 0xb5, 0xd8, 0x8e, 0x6c, 0xb7, 0x6a, 0xdf, 0x82, 0x37, 0xe1, 0xc2,
	0x43, 0x70, 0x9c, 0x38, 0x71, 0x44, 0xed, 0x8b, 0xa0, 0xa6, 0x76, 0x27, 0x95, 0xa0, 0xdd, 0xe2,
	0xef, 0xf7, 0x7d, 0xf9, 0xfc, 0x77, 0x1c, 0x08, 0x12, 0x9c, 0x2c, 0x72, 0xc1, 0xc3, 0x44, 0xa7,
	0x4a, 0xdf, 0xa4, 0x82, 0xab, 0x29, 0x23, 0x32, 0x9c, 0xf5, 0x76, 0x94, 0xa0, 0x90, 0x42, 0x0b,
	0xd4, 0x32, 0xfe, 0x60, 0x87, 0xce, 0x7a, 0x4f, 0x5a, 0xa9, 0x50, 0x4c, 0xa8, 0xb8, 0x34, 0x86,
	0x9b, 0xc5, 0x26, 0xd5, 0xf9, 0xbe, 0x07, 0xf5, 0x81, 0xb1, 0x46, 0x64, 0x42, 0x95, 0x26, 0x12,
	0x3d, 0x83, 0x03, 0x1b, 0x8f, 0x69, 0xe6, 0xb9, 0x6d, 0xb7, 0xbb, 0x1f, 0x81, 0x95, 0xce, 0x32,
	0xf4, 0x1c, 0x8e, 0xb6, 0x06, 0x8e, 0x19, 0xf1, 0x1e, 0x94, 0x96, 0x43, 0x2b, 0x7e, 0xc6, 0x8c,
	0xa0, 0x1e, 0x34, 0xb6, 0xa6, 0x8c, 0xa8, 0x54, 0xd2, 0x42, 0x53, 0xc1, 0xbd, 0xbd, 0xd2, 0x7b,
	0x62, 0xd9, 0x87, 0x3b, 0x84, 0x42, 0x68, 0x30, 0x3c, 0x8f, 0xd9, 0x34, 0xd7, 0x34, 0x56, 0x1a,
	0xdf, 0x90, 0x2c, 0xbe, 0x2a, 0x94, 0xf7, 0xb0, 0xed, 0x76, 0x8f, 0xa2, 0x63, 0x86, 0xe7, 0xc3,
	0x35, 0x1a, 0x97, 0xe4, 0x63, 0xa1, 0x10, 0x03, 0xcf, 0xcc, 0xb6, 0xad, 0x62, 0x44, 0xe3, 0x0c,
	0x6b, 0xec, 0x3d, 0x6a, 0xbb, 0xdd, 0x83, 0x57, 0xbd, 0xe0, 0xbf, 0xe7, 0x12, 0x0c, 0xca, 0xa8,
	0x1d, 0x7f, 0x68, 0x82, 0x9f, 0x9c, 0xa8, 0x99, 0x56, 0x92, 0x75, 0x9d, 0x14, 0x79, 0x3e, 0x2d,
	0x2a, 0xea, 0x6a, 0xf7, 0xd6, 0x45, 0x65, 0xb4, 0xaa, 0x4e, 0x56, 0x92, 0xfe, 0x09, 0x1c, 0xff,
	0xd3, 0xd3, 0x79, 0x0b, 0xcd, 0xea, 0x7d, 0xa3, 0xa7, 0x00, 0xe9, 0x35, 0xe6, 0x9c, 0xe4, 0x77,
	0x5f, 0x6d, 0xdf, 0x28, 0x67, 0x59, 0x87, 0x43, 0xb3, 0x7a, 0x07, 0xe8, 0x02, 0x5a, 0x57, 0x94,
	0xe3, 0x9c, 0xea, 0xc5, 0x7a, 0x30, 0x2d, 0x71, 0xaa, 0x63, 0x9c, 0x65, 0x92, 0x28, 0xb5, 0x79,
	0x4f, 0xdf, 0xfb, 0xf5, 0xe3, 0xb4, 0x61, 0x6e, 0xce, 0xfb, 0x0d, 0x19, 0x6b, 0x49, 0xf9, 0x24,
	0x7a, 0x6c, 0xa3, 0x03, 0x93, 0x34, 0xf8, 0xe5, 0x0b, 0x38, 0xb4, 0x4d, 0x17, 0x8b, 0x82, 0x20,
	0x80, 0xda, 0x60, 0x34, 0x1e, 0x8e, 0xc6, 0x75, 0x67, 0xfd, 0x1c, 0x8d, 0xce, 0xcf, 0x2f, 0xbf,
	0xd4, 0xdd, 0xfe, 0xe5, 0xcf, 0xa5, 0xef, 0xde, 0x2e, 0x7d, 0xf7, 0xcf, 0xd2, 0x77, 0xbf, 0xad,
	0x7c, 0xe7, 0x76, 0xe5, 0x3b, 0xbf, 0x57, 0xbe, 0xf3, 0xf5, 0xdd, 0x84, 0xea, 0xeb, 0x69, 0x12,
	0xa4, 0x82, 0x85, 0xe6, 0x58, 0x73, 0x9c, 0xa8, 0x53, 0x2a, 0xec, 0x32, 0x9c, 0xbd, 0x09, 0xe7,
	0xbb, 0x7f, 0x88, 0x5e, 0x14, 0x44, 0x25, 0xb5, 0xf2, 0x82, 0xbf, 0xfe, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x53, 0xd2, 0xb0, 0x14, 0x48, 0x03, 0x00, 0x00,
}

func (m *ConsumerRegister) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsumerRegister) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerRegister) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ConsumerMetadata != nil {
		{
			size := m.ConsumerMetadata.Size()
			i -= size
			if _, err := m.ConsumerMetadata.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.MaxMultiStakedFps != 0 {
		i = encodeVarintBtcstkconsumer(dAtA, i, uint64(m.MaxMultiStakedFps))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ConsumerDescription) > 0 {
		i -= len(m.ConsumerDescription)
		copy(dAtA[i:], m.ConsumerDescription)
		i = encodeVarintBtcstkconsumer(dAtA, i, uint64(len(m.ConsumerDescription)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConsumerName) > 0 {
		i -= len(m.ConsumerName)
		copy(dAtA[i:], m.ConsumerName)
		i = encodeVarintBtcstkconsumer(dAtA, i, uint64(len(m.ConsumerName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ConsumerId) > 0 {
		i -= len(m.ConsumerId)
		copy(dAtA[i:], m.ConsumerId)
		i = encodeVarintBtcstkconsumer(dAtA, i, uint64(len(m.ConsumerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConsumerRegister_CosmosConsumerMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerRegister_CosmosConsumerMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CosmosConsumerMetadata != nil {
		{
			size, err := m.CosmosConsumerMetadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBtcstkconsumer(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *ConsumerRegister_RollupConsumerMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerRegister_RollupConsumerMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.RollupConsumerMetadata != nil {
		{
			size, err := m.RollupConsumerMetadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBtcstkconsumer(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	return len(dAtA) - i, nil
}
func (m *CosmosConsumerMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CosmosConsumerMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CosmosConsumerMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintBtcstkconsumer(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RollupConsumerMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RollupConsumerMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RollupConsumerMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FinalityContractAddress) > 0 {
		i -= len(m.FinalityContractAddress)
		copy(dAtA[i:], m.FinalityContractAddress)
		i = encodeVarintBtcstkconsumer(dAtA, i, uint64(len(m.FinalityContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBtcstkconsumer(dAtA []byte, offset int, v uint64) int {
	offset -= sovBtcstkconsumer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ConsumerRegister) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConsumerId)
	if l > 0 {
		n += 1 + l + sovBtcstkconsumer(uint64(l))
	}
	l = len(m.ConsumerName)
	if l > 0 {
		n += 1 + l + sovBtcstkconsumer(uint64(l))
	}
	l = len(m.ConsumerDescription)
	if l > 0 {
		n += 1 + l + sovBtcstkconsumer(uint64(l))
	}
	if m.MaxMultiStakedFps != 0 {
		n += 1 + sovBtcstkconsumer(uint64(m.MaxMultiStakedFps))
	}
	if m.ConsumerMetadata != nil {
		n += m.ConsumerMetadata.Size()
	}
	return n
}

func (m *ConsumerRegister_CosmosConsumerMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CosmosConsumerMetadata != nil {
		l = m.CosmosConsumerMetadata.Size()
		n += 1 + l + sovBtcstkconsumer(uint64(l))
	}
	return n
}
func (m *ConsumerRegister_RollupConsumerMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RollupConsumerMetadata != nil {
		l = m.RollupConsumerMetadata.Size()
		n += 1 + l + sovBtcstkconsumer(uint64(l))
	}
	return n
}
func (m *CosmosConsumerMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovBtcstkconsumer(uint64(l))
	}
	return n
}

func (m *RollupConsumerMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FinalityContractAddress)
	if l > 0 {
		n += 1 + l + sovBtcstkconsumer(uint64(l))
	}
	return n
}

func sovBtcstkconsumer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBtcstkconsumer(x uint64) (n int) {
	return sovBtcstkconsumer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ConsumerRegister) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBtcstkconsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsumerRegister: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsumerRegister: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBtcstkconsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBtcstkconsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBtcstkconsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMultiStakedFps", wireType)
			}
			m.MaxMultiStakedFps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBtcstkconsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMultiStakedFps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosConsumerMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBtcstkconsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CosmosConsumerMetadata{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.ConsumerMetadata = &ConsumerRegister_CosmosConsumerMetadata{v}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupConsumerMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBtcstkconsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &RollupConsumerMetadata{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.ConsumerMetadata = &ConsumerRegister_RollupConsumerMetadata{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBtcstkconsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CosmosConsumerMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBtcstkconsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CosmosConsumerMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CosmosConsumerMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBtcstkconsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBtcstkconsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RollupConsumerMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBtcstkconsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RollupConsumerMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RollupConsumerMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalityContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBtcstkconsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalityContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBtcstkconsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBtcstkconsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBtcstkconsumer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBtcstkconsumer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBtcstkconsumer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBtcstkconsumer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBtcstkconsumer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBtcstkconsumer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBtcstkconsumer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBtcstkconsumer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBtcstkconsumer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBtcstkconsumer = fmt.Errorf("proto: unexpected end of group")
)
