name: Changelog Reminder
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

permissions:
  contents: read

jobs:
  changelog_reminder:
    uses: babylonlabs-io/.github/.github/workflows/reusable_changelog_reminder.yml@5d014a155c08d56a1b5673d049f2b4e7d4427825 # v0.19.0 https://github.com/babylonlabs-io/.github/releases/tag/v0.19.0
    secrets: inherit
