name: goreleaser

on:
  push:
    branches:
      - 'hiep/test-build'

permissions:
  contents: write

jobs:
  goreleaser:
    name: Create release
    runs-on: ubuntu-24.04-8core
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make release
        run: |
          make release-dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
