name: goreleaser

on:
  release:
    types: [published]
  push:
    branches:
      - hiep-build
permissions:
  contents: write

jobs:
  goreleaser:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout the specified tag
        run: |
          git fetch --tags
          git checkout v1.0.2
      - name: Make release
        run: |
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
