name: Create Sync PR from main to base/consumer-chain-support

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  pull-requests: write

jobs:
  call_sync_branch:
    uses: babylonlabs-io/.github/.github/workflows/reusable_sync_branch.yml@5d014a155c08d56a1b5673d049f2b4e7d4427825 # v0.19.0 https://github.com/babylonlabs-io/.github/releases/tag/v0.19.0
    with:
      base_branch: "main"
      target_branch: "base/consumer-chain-support"
      reviewers: "SebastianElvis,maurolacy,gusin13"
    secrets: inherit
