name: Create Sync PR from main to base/consumer-chain-support

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  pull-requests: write

jobs:
  call_sync_branch:
    uses: babylonlabs-io/.github/.github/workflows/reusable_sync_branch.yml@98e4de18638b3d0738c9cbf7e7dfc6e34524db54 # v0.19.1 https://github.com/babylonlabs-io/.github/releases/tag/v0.19.1
    with:
      base_branch: "main"
      target_branch: "base/consumer-chain-support"
      reviewers: "SebastianElvis,maurolacy,gusin13"
    secrets: inherit
